import { z } from 'zod';
const time = z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/);
export const profileSchema=z.object({paperMm:z.enum(['48','58','80']),width:z.number().int().min(128).max(576),characters:z.number().int().min(16).max(64),fontSize:z.number().int().min(16).max(40),lineSpacing:z.number().min(1).max(3),margin:z.number().int().min(0).max(32),feed:z.number().int().min(0).max(200),cut:z.boolean(),bitmapThai:z.boolean()});
export const blockSchema=z.object({id:z.string(),type:z.enum(['LOGO','INSTITUTION_NAME','STORE_NAME','CUSTOM_HEADER','ORDER_INFORMATION','ITEM_TABLE','SUBTOTAL','DISCOUNT','TOTAL','PAYMENT','CHANGE','QUEUE_NUMBER','CASHIER','CUSTOM_MESSAGE','QR_CODE','BARCODE','CUSTOM_FOOTER']),visible:z.boolean(),align:z.enum(['LEFT','CENTER','RIGHT']),size:z.enum(['SMALL','NORMAL','LARGE','EXTRA_LARGE']),bold:z.boolean(),before:z.number().int().min(0).max(5),after:z.number().int().min(0).max(5),divider:z.boolean(),text:z.string().max(1000)});
export const settingsSchema=z.object({systemName:z.string().min(1).max(100),organization:z.string().min(1).max(200),storeName:z.string().max(200),opening:time,closing:time,queuePrefix:z.string().regex(/^[A-Z]{1,4}$/),header:z.string().max(1000),footer:z.string().max(1000),logo:z.string().max(500000),qr:z.string().max(1000),autoPrint:z.boolean(),copies:z.number().int().min(1).max(3),profile:profileSchema,blocks:z.array(blockSchema).max(30)}).refine(s=>s.opening<s.closing,{message:'เวลาเริ่มวันทำการต้องก่อนเวลาปิดร้าน'});
export type Settings=z.infer<typeof settingsSchema>;
export type Profile=z.infer<typeof profileSchema>;
export type Block=z.infer<typeof blockSchema>;
export const defaultSettings:Settings={systemName:'CIDA POS',organization:'ทัณฑสถานบำบัดพิเศษกลาง',storeName:'จุดจำหน่ายอาหารและสินค้า',opening:'00:00',closing:'23:59',queuePrefix:'A',header:'ฝ่ายฝึกวิชาชีพผู้ต้องขัง\nส่วนพัฒนาผู้ต้องขัง',footer:'ขอบคุณที่ใช้บริการ',logo:'',qr:'',autoPrint:true,copies:1,profile:{paperMm:'80',width:576,characters:48,fontSize:24,lineSpacing:1,margin:0,feed:80,cut:false,bitmapThai:false},blocks:['INSTITUTION_NAME','CUSTOM_HEADER','ORDER_INFORMATION','ITEM_TABLE','SUBTOTAL','DISCOUNT','TOTAL','PAYMENT','CHANGE','QUEUE_NUMBER','CASHIER','CUSTOM_FOOTER'].map((type,i)=>({id:`block-${i}`,type:type as Block['type'],visible:true,align:['INSTITUTION_NAME','CUSTOM_HEADER','QUEUE_NUMBER','CUSTOM_FOOTER'].includes(type)?'CENTER':'LEFT',size:type==='QUEUE_NUMBER'?'EXTRA_LARGE':type==='TOTAL'?'LARGE':'NORMAL',bold:['TOTAL','QUEUE_NUMBER','INSTITUTION_NAME'].includes(type),before:0,after:type==='QUEUE_NUMBER'?1:0,divider:['ORDER_INFORMATION','ITEM_TABLE','TOTAL'].includes(type),text:''}))};
