import type {Settings} from './config';
import type {Actor} from './auth';
import type {summarize} from './domain';
export type Category={id:string;name:string;icon:string;color:string;shortcut:string;preparationArea:string;sort:number;active:boolean};
export type Modifier={id:string;name:string;price:number;active:boolean;sort:number};
export type Product={id:string;sku:string;barcode:string|null;name:string;description:string;categoryId:string;price:number;cost:number;image:string;active:boolean;available:boolean;favorite:boolean;featured:boolean;sort:number;modifiers:Modifier[];category?:Category};
export type Terminal={id:string;name:string;location:string;active:boolean;config:{printerId:string;adapter:'imin'|'mock'|'browser'|'codesoft';connection:'USB'|'SPI'|'Bluetooth';sdkPath:string;drawer:boolean;cutter:boolean;sound:boolean;density:'comfortable'|'compact';fallbackPrinter?:'codesoft'|'browser';codesoftPaperMm?:'58'|'80';drawerDevice?:'printer'|'imin'}};
export type CartLine={productId:string;quantity:number;modifiers:string[];note:string};
export type Catalog={user:Actor;salesVersion?:string;config:Settings;categories:Category[];products:Product[];terminals:Terminal[]};
export type Receipt={orderId?:string;number?:string;queue?:string;date:string;cashier?:string;terminal:string;subtotal?:number;discount?:number;total?:number;items?:{name:string;quantity:number;unitPrice:number;lineTotal:number;note:string;modifiers:{name:string;price:number}[]}[];payments?:{method:string;amount:number;received:number;change:number}[];config:Settings;isReprint?:boolean;kitchen?:boolean;test?:boolean;dailyReport?:{businessDate:string;closed:boolean;opening:string;summary:ReturnType<typeof summarize>}};
export type PrintJob={id:string;orderId:string|null;terminalId:string;printerId:string;template:string;status:string;profile:Settings['profile'];payload:Receipt;claimToken?:string;error?:string;createdAt:string};
