import {test,expect,type Page} from '@playwright/test';
import type {Catalog} from '../../src/lib/types';
try{process.loadEnvFile('.env');}catch{}
async function setup(page:Page,{offline=false,retry=false,duplicate=false}={}){
 expect((await page.request.post('/api/login',{headers:{Origin:'http://localhost:3000'},data:{username:'cashier',password:process.env.SEED_CASHIER_PASSWORD},timeout:120000})).ok()).toBe(true);
 const catalog:Catalog=await(await page.request.get('/api/catalog',{timeout:120000})).json(),base=catalog.products[0],cat=catalog.categories[0],other=catalog.categories[1];
 const terminal={...catalog.terminals[0],config:{...catalog.terminals[0].config,adapter:'mock' as const,drawer:false}};
 const data:Catalog={...catalog,terminals:[terminal],config:{...catalog.config,autoPrint:true},categories:[{...cat,shortcut:'1'},{...other,shortcut:'2'}],products:[{...base,id:'ux-ice',name:'ไอศกรีมทดสอบ',price:7000,sku:'UX-ICE',barcode:'880001',categoryId:cat.id,image:'',modifiers:[],favorite:true,available:true,active:true},{...base,id:'ux-water',name:'น้ำทดสอบ',price:3000,sku:'UX-WATER',barcode:'880002',categoryId:other.id,image:'',modifiers:[],available:true,active:true},{...base,id:'ux-sold-out',name:'สินค้าหมดทดสอบ',price:1000,sku:'UX-SOLD',barcode:'880003',categoryId:cat.id,image:'',modifiers:[],available:false,active:true}]};
 if(duplicate)data.products[1].barcode='880001';
 const checkouts:any[]=[],printResults:any[]=[];let healthy=!offline;
 await page.route('**/api/catalog',route=>route.fulfill({json:data}));await page.route('**/api/health',route=>route.fulfill({status:healthy?200:503,json:{ok:healthy,error:'ทดสอบขาดการเชื่อมต่อ'}}));await page.route('**/api/print-jobs?*',route=>route.fulfill({json:[]}));
 await page.route('**/api/checkout',route=>{const body=route.request().postDataJSON();checkouts.push(body);if(retry&&checkouts.length===1)return route.fulfill({status:503,json:{error:'ทดสอบเครือข่าย กรุณาตรวจสอบคำขอเดิม'}});const payload={number:'UX-BILL-001',queue:'A007',terminal:terminal.name,date:new Date().toISOString(),total:body.payments[0].amount,payments:[{...body.payments[0],change:body.payments[0].received-body.payments[0].amount}],config:data.config};return route.fulfill({json:{order:{...payload,id:'ux-order'},jobs:[{id:'ux-print',printerId:terminal.config.printerId,terminalId:terminal.id,orderId:'ux-order',template:'CUSTOMER',status:'PENDING',profile:data.config.profile,payload}]}});});
 await page.route('**/api/print-jobs/ux-print/claim',route=>route.fulfill({json:{claimToken:'ux-claim'}}));await page.route('**/api/print-jobs/ux-print/result',route=>{printResults.push(route.request().postDataJSON());return route.fulfill({json:{ok:true}});});
 await page.goto('/pos');await expect(page.locator('.product-card')).toHaveCount(3);return {data,checkouts,printResults,reconnect:()=>{healthy=true;}};
}
async function addIce(page:Page){await page.locator('.product-card').filter({has:page.getByRole('heading',{name:'ไอศกรีมทดสอบ',exact:true})}).click();}
test('scanner adds exact barcode across categories and preserves focus for the next scan',async({page})=>{
 const {data,checkouts}=await setup(page);await page.locator('.category-sidebar').getByRole('button',{name:data.categories[0].name+' 1',exact:true}).click();const search=page.getByRole('textbox',{name:'ค้นหาสินค้า'});await search.fill('880002');await expect(page.locator('.product-card')).toHaveCount(1);await search.press('Enter');await expect(page.getByLabel('จำนวน น้ำทดสอบ',{exact:true})).toHaveValue('1');await expect(search).toHaveValue('');await expect(search).toBeFocused();await search.fill('UX-ICE');await search.press('Enter');await expect(page.getByLabel('จำนวน ไอศกรีมทดสอบ',{exact:true})).toHaveValue('1');await search.press('F9');await expect(page.getByRole('dialog',{name:'รับชำระเงิน'})).toBeVisible();await page.getByRole('dialog').getByRole('button',{name:'ปิด',exact:true}).click();await expect(search).toBeFocused();expect(checkouts).toHaveLength(0);
});
test('unknown, ambiguous and unavailable scans never add a wrong product',async({page})=>{
 const {data}=await setup(page,{duplicate:true}),search=page.getByRole('textbox',{name:'ค้นหาสินค้า'});await search.fill('880003');await search.press('Enter');await expect(page.locator('.pos-messages').getByRole('alert')).toContainText('ยังไม่พร้อมขาย');await search.fill('123456');await search.press('Enter');await expect(page.locator('.pos-messages').getByRole('alert')).toContainText('ไม่พบรหัสนี้');await search.fill('880001');await search.press('Enter');await expect(page.locator('.pos-messages').getByRole('alert')).toContainText('รหัสสินค้าซ้ำ');await expect(page.locator('.cart-line')).toHaveCount(0);
});
test('staff can undo a removal with its quantity and note intact',async({page})=>{
 await setup(page);await addIce(page);await page.getByLabel('จำนวน ไอศกรีมทดสอบ',{exact:true}).fill('3');await page.getByRole('button',{name:'ตัวเลือก / หมายเหตุ',exact:true}).click();await page.getByRole('dialog').getByLabel('หมายเหตุ',{exact:true}).fill('แยกถุง');await page.getByRole('button',{name:'เรียบร้อย',exact:true}).click();await page.getByRole('button',{name:'ลบ ไอศกรีมทดสอบ',exact:true}).click();await expect(page.locator('.cart-line')).toHaveCount(0);await page.getByRole('button',{name:'คืนรายการ',exact:true}).click();await expect(page.getByLabel('จำนวน ไอศกรีมทดสอบ',{exact:true})).toHaveValue('3');await expect(page.locator('.cart-line')).toContainText('แยกถุง');
});
test('typing category shortcut numbers in the bill note does not change categories',async({page})=>{
 const {data}=await setup(page);await page.locator('.category-sidebar').getByRole('button',{name:data.categories[0].name+' 1',exact:true}).click();await addIce(page);await page.getByRole('textbox',{name:'หมายเหตุบิล',exact:true}).pressSequentially('2121');await expect(page.locator('.category-sidebar').getByRole('button',{name:data.categories[0].name+' 1',exact:true})).toHaveAttribute('aria-pressed','true');await expect(page.getByRole('textbox',{name:'หมายเหตุบิล',exact:true})).toHaveValue('2121');
});
test('cash shortfall and invalid precision block checkout; sale summary survives receipt success',async({page})=>{
 const {checkouts,printResults}=await setup(page);await addIce(page);await page.getByRole('button',{name:'ชำระเงิน',exact:true}).click();const input=page.getByLabel('รับเงิน (บาท)',{exact:true}),confirm=page.getByRole('button',{name:'รับชำระเงิน',exact:true});await input.fill('50');await expect(page.locator('.cash-shortfall')).toContainText('20.00');await expect(confirm).toBeDisabled();await input.fill('100.001');await expect(confirm).toBeDisabled();await input.press('Enter');expect(checkouts).toHaveLength(0);await input.fill('');await expect(confirm).toBeDisabled();await page.getByRole('button',{name:'100',exact:true}).click();await expect(page.locator('.change')).toContainText('30.00');await confirm.click();await expect.poll(()=>printResults.length).toBe(1);await expect(page.getByRole('status',{name:'สรุปบิลที่ชำระแล้ว'})).toContainText('A007');await expect(page.getByRole('status',{name:'สรุปบิลที่ชำระแล้ว'})).toContainText('30.00');expect(checkouts).toHaveLength(1);await expect(page.locator('.cart-line')).toHaveCount(0);
});
test('Enter on a payment method changes the method without submitting a sale',async({page})=>{
 const {checkouts}=await setup(page);await addIce(page);await page.getByRole('button',{name:'ชำระเงิน',exact:true}).click();const qr=page.getByRole('button',{name:'QR / โอน',exact:true});await qr.focus();await qr.press('Enter');await expect(qr).toHaveAttribute('aria-pressed','true');expect(checkouts).toHaveLength(0);await page.getByLabel('เลขอ้างอิงการชำระ').fill('REF-UX');await page.getByRole('button',{name:'รับชำระเงิน',exact:true}).click();await expect.poll(()=>checkouts.length).toBe(1);expect(checkouts[0].payments[0]).toMatchObject({method:'QR',amount:7000,received:7000,reference:'REF-UX'});
});
for(const viewport of [{width:390,height:844},{width:360,height:640}])test(`mobile ${viewport.width} bill tab opens the cart without scrolling through the menu`,async({page})=>{
 await page.setViewportSize(viewport);await setup(page);await addIce(page);const nav=page.getByRole('navigation',{name:'หน้าขายบนมือถือ'});await expect(nav).toBeInViewport();await nav.getByRole('button',{name:/ดูบิล/}).click();await expect(page.locator('.cart-panel')).toBeVisible();await expect(page.locator('.products-panel')).toBeHidden();await expect(page.getByRole('button',{name:'ชำระเงิน',exact:true})).toBeInViewport();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await nav.getByRole('button',{name:'เลือกสินค้า',exact:true}).click();await expect(page.locator('.products-panel')).toBeVisible();await expect(page.locator('.cart-panel')).toBeHidden();await page.screenshot({path:`test-results/pos-upgraded-mobile-${viewport.width}.png`});
});
test('offline bill stays intact and reconnect restores payment',async({page})=>{
 const {checkouts,reconnect}=await setup(page,{offline:true});await expect(page.locator('.pos-offline')).toBeVisible();await addIce(page);await expect(page.getByRole('button',{name:'ชำระเงิน',exact:true})).toBeDisabled();expect(checkouts).toHaveLength(0);reconnect();await page.getByRole('button',{name:'เชื่อมต่อใหม่',exact:true}).click();await expect(page.locator('.pos-offline')).toBeHidden();await expect(page.getByRole('button',{name:'ชำระเงิน',exact:true})).toBeEnabled();await expect(page.getByLabel('จำนวน ไอศกรีมทดสอบ',{exact:true})).toHaveValue('1');
});
test('uncertain checkout survives refresh and retries the same key and tender',async({page})=>{
 const {checkouts}=await setup(page,{retry:true});await addIce(page);await page.getByRole('button',{name:'ชำระเงิน',exact:true}).click();await page.getByRole('button',{name:'100',exact:true}).click();await page.getByRole('button',{name:'รับชำระเงิน',exact:true}).click();await expect.poll(()=>checkouts.length).toBe(1);await page.reload();await expect(page.getByRole('button',{name:'ตรวจสอบ / ส่งคำขอเดิม',exact:true})).toBeEnabled();await page.getByRole('button',{name:'ตรวจสอบ / ส่งคำขอเดิม',exact:true}).click();await expect.poll(()=>checkouts.length).toBe(2);expect(checkouts[1]).toEqual(checkouts[0]);await expect(page.locator('.sale-confirmation')).toContainText('30.00');
});
test('help explains the selling flow and cannot trigger checkout',async({page})=>{
 const {checkouts}=await setup(page);await page.getByRole('button',{name:'วิธีใช้งาน',exact:true}).click();const help=page.getByRole('dialog',{name:'เริ่มขายใน 3 ขั้นตอน'});await expect(help).toContainText('ไม่ต้องรับชำระใหม่');await help.press('F9');expect(checkouts).toHaveLength(0);await help.getByRole('button',{name:'เริ่มขาย',exact:true}).click();await expect(help).toHaveCount(0);await page.screenshot({path:'test-results/pos-upgraded-desktop.png'});
});
