import {test,expect,type Page} from '@playwright/test';
try{process.loadEnvFile('.env');}catch{}
async function installPrinter(page:Page,status:number){await page.addInitScript(status=>{window.IminPrintInstance={initPrinter(){},getPrinterStatus:async()=>({value:status}),setTextWidth(){},setPageFormat(){},setAlignment(){},setTextSize(){},printText(){},printAndFeedPaper(){},printSingleBitmap:async()=>{},partialCut(){},printQrCode(){},printBarCode(){}};},status);}
test('cashier checkout, refresh recovery and printer failure preserve a single sale',async({page})=>{
 await installPrinter(page,7);
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/login');await page.getByLabel('ชื่อผู้ใช้งาน').fill('cashier');await page.getByLabel('รหัสผ่าน').fill(process.env.SEED_CASHIER_PASSWORD!);await page.getByRole('button',{name:'เข้าสู่ระบบ',exact:true}).click();await expect(page).toHaveURL(/\/pos/,{timeout:15000});await expect(page.locator('.product-card')).toHaveCount(91);
 await page.getByRole('button',{name:/อาหารร้านนอก F1/}).click();await page.locator('.product-card').filter({hasText:'หมูปิ้งนมสด'}).click({clickCount:2});await expect(page.getByLabel('จำนวน หมูปิ้งนมสด',{exact:true})).toHaveValue('2');await page.getByRole('button',{name:/อาหารหน้าร้าน F2/}).click();await page.locator('.product-card').filter({has:page.getByRole('heading',{name:'ข้าวสวย',exact:true})}).click();await expect(page.locator('.cart-total')).toContainText('170.00');
 await page.reload();await expect(page.getByLabel('จำนวน หมูปิ้งนมสด',{exact:true})).toHaveValue('2');
 await page.getByRole('button',{name:'ชำระเงิน',exact:true}).click();await page.getByRole('button',{name:'200',exact:true}).click();await expect(page.locator('.change')).toContainText('30.00');await page.getByRole('button',{name:'รับชำระเงิน',exact:true}).click();await expect(page.locator('.cart-empty')).toBeVisible();await expect(page.locator('.notice')).toContainText('ชำระสำเร็จ');await expect(page.locator('.print-recovery')).toBeVisible({timeout:15000});await page.screenshot({path:'test-results/pos-1366.png',fullPage:true});
 const before=await page.request.get('/api/orders');const orders=await before.json();const order=orders.orders[0];expect(order.total).toBe(17000);expect(order.items.find((i:{name:string})=>i.name==='หมูปิ้งนมสด').quantity).toBe(2);
 await page.evaluate(()=>{window.IminPrintInstance={PrintConnectType:{USB:'USB',SPI:'SPI',Bluetooth:'Bluetooth'},initPrinter(){},getPrinterStatus:async()=>({value:0}),setTextWidth(){},setPageFormat(){},setAlignment(){},setTextSize(){},printText(){},printAndFeedPaper(){},printSingleBitmap:async()=>{},partialCut(){}};});
 await page.getByRole('button',{name:'บิลล่าสุด',exact:true}).click();const printResponse=page.waitForResponse(r=>r.url().includes('/result')&&r.request().method()==='POST');await page.locator('.list-row').filter({hasText:order.number}).getByRole('button',{name:'พิมพ์ซ้ำ'}).click();expect((await printResponse).status()).toBe(200);await page.getByRole('button',{name:'ปิด',exact:true}).last().click();const after=await page.request.get('/api/orders');expect((await after.json()).count).toBe(orders.count);
 const forbidden=await page.request.post('/api/settings',{headers:{Origin:'http://localhost:3000'},data:{}});expect(forbidden.status()).toBe(403);expect(errors).toEqual([]);
});
test('lost checkout response retries original key after commit',async({page})=>{
 await installPrinter(page,0);
 await page.goto('/login');await page.getByLabel('ชื่อผู้ใช้งาน').fill('cashier');await page.getByLabel('รหัสผ่าน').fill(process.env.SEED_CASHIER_PASSWORD!);await page.getByRole('button',{name:'เข้าสู่ระบบ',exact:true}).click();await expect(page).toHaveURL(/\/pos/,{timeout:15000});await expect(page.locator('.product-card')).toHaveCount(91);const initial=await (await page.request.get('/api/orders')).json();
 await page.locator('.product-card').filter({has:page.getByRole('heading',{name:'ข้าวสวย',exact:true})}).click();await page.getByRole('button',{name:'ชำระเงิน',exact:true}).click();await page.route('**/api/checkout',async route=>{const result=await route.fetch();expect(result.ok()).toBe(true);await route.abort('connectionreset');});await page.getByRole('button',{name:'รับชำระเงิน',exact:true}).click();await expect(page.getByRole('button',{name:'ตรวจสอบ / ส่งคำขอเดิม'})).toBeVisible();await page.unroute('**/api/checkout');await page.reload();await expect(page.getByRole('button',{name:'ตรวจสอบ / ส่งคำขอเดิม'})).toBeVisible();await expect(page.getByRole('button',{name:'ตรวจสอบ / ส่งคำขอเดิม'})).toBeEnabled();await page.getByRole('button',{name:'ตรวจสอบ / ส่งคำขอเดิม'}).click();await expect(page.locator('.cart-empty')).toBeVisible();const final=await (await page.request.get('/api/orders')).json();expect(final.count).toBe(initial.count+1);
});
test('admin reports, receipt designer and responsive pages load',async({page})=>{
 await page.goto('/login');await page.getByLabel('ชื่อผู้ใช้งาน').fill('admin');await page.getByLabel('รหัสผ่าน').fill(process.env.SEED_ADMIN_PASSWORD!);await page.getByRole('button',{name:'เข้าสู่ระบบ',exact:true}).click();await expect(page).toHaveURL(/\/pos/,{timeout:15000});await page.goto('/admin/dashboard');await expect(page.locator('.kpi')).toHaveCount(4);await expect(page.locator('.category-report').getByText('ยอดขายแยกตามหมวดสินค้า',{exact:true})).toBeVisible();await page.screenshot({path:'test-results/dashboard-1366.png',fullPage:true});await page.goto('/admin/settings');await expect(page.locator('.receipt-paper')).toContainText('ทัณฑสถานบำบัดพิเศษกลาง');await page.locator('label').filter({hasText:'ท้ายบิล'}).getByRole('textbox').fill('ขอบคุณสำหรับการใช้บริการ');await expect(page.locator('.receipt-paper')).toContainText('ขอบคุณสำหรับการใช้บริการ');await page.screenshot({path:'test-results/receipt-designer.png',fullPage:true});
 for(const route of ['products','categories','orders','reports','snapshots','closings','users','audit']){await page.goto('/admin/'+route);await expect(page.locator('.page-heading h1')).toBeVisible();await expect(page.locator('.loading')).toHaveCount(0,{timeout:15000});}
 await page.goto('/admin/products');const products=await (await page.request.get('/api/products')).json();const chicken=products.find((p:{name:string})=>p.name==='หมูปิ้งนมสด');const row=page.getByRole('row').filter({has:page.getByText('หมูปิ้งนมสด',{exact:true})});await row.getByRole('button',{name:'แก้ไข'}).click();await page.getByLabel('ราคาขาย (บาท)',{exact:true}).fill('55');await page.getByRole('button',{name:'บันทึกสินค้า',exact:true}).click();await expect(page.locator('dialog')).toHaveCount(0);const updated=await (await page.request.get('/api/products')).json();expect(updated.find((p:{id:string})=>p.id===chicken.id).modifiers.map((m:{id:string})=>m.id)).toEqual(chicken.modifiers.map((m:{id:string})=>m.id));await page.request.post('/api/products/'+chicken.id,{headers:{Origin:'http://localhost:3000'},data:chicken});await page.goto('/admin/audit');await expect(page.locator('table').getByText('PRICE_CHANGE',{exact:true}).first()).toBeVisible();
 await page.setViewportSize({width:390,height:844});await page.goto('/pos');await expect(page.locator('.product-card').first()).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.screenshot({path:'test-results/pos-mobile.png',fullPage:true});
});
