import {test,before,after} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {hash as passwordHash} from 'bcryptjs';
import {db} from '../src/lib/db';
import {isolatedCloudflare} from './cloudflare-fixture';
import {checkout,adjustOrder,report,salesTrend,closeDay,reopenDay,reprint,claimJob,dailyReportPrint,settings,json} from '../src/lib/sales';
import type {Actor} from '../src/lib/auth';
import {defaultSettings} from '../src/lib/config';
import type {Checkout} from '../src/lib/validation';
import {businessDate,summarize} from '../src/lib/domain';
import {resetPreview,resetSales,resetArchive,resetArchives} from '../src/lib/sales-reset';
import {seedMenu} from '../prisma/menu-seed';
import menuData from '../prisma/menu-data.json';
try{process.loadEnvFile('.env');}catch{}
const enabled=process.env.RUN_DB_TESTS==='true';
let cloud:Awaited<ReturnType<typeof isolatedCloudflare>>|undefined;
before(async()=>{if(enabled)cloud=await isolatedCloudflare();});
after(async()=>{await cloud?.mf.dispose();});
test('transactional sales, retries, refunds, close locks and immutable audit on D1',{skip:!enabled},async()=>{
 const suffix=randomUUID().slice(0,8),user=await db.user.create({data:{username:`test-${suffix}`,name:'INTEGRATION TEST',role:'SUPER_ADMIN',passwordHash:'not-a-login'}});const actor:Actor={id:user.id,name:user.name,role:user.role,username:user.username};
 const category=await db.category.create({data:{name:`TEST ${suffix}`,icon:'Package'}});const product=await db.product.create({data:{sku:`TEST-${suffix}`,name:'TEST กะเพรา',categoryId:category.id,price:5000,modifiers:{create:[{name:'ไข่ดาว',price:1000}] }},include:{modifiers:true}});
 const terminal=await db.terminal.create({data:{id:`TEST-${suffix}`,name:'TEST terminal',config:{printerId:'mock',adapter:'mock'}}});
 const config=await settings(),date=businessDate(new Date(),config.opening);const priorDay=await db.businessDay.findUnique({where:{date}});assert.notEqual(priorDay?.closed,true,'Run integration tests against an open test database');
 const legacyConfig={...config,storeName:'Original shop',profile:{...config.profile,paperMm:'58' as const,width:384,characters:32}};
 await db.setting.upsert({where:{key:'system'},create:{key:'system',value:json(legacyConfig)},update:{value:json(legacyConfig)}});
 const input:Checkout={key:randomUUID(),salesVersion:((await db.setting.findUnique({where:{key:'sales-version'}}))?.value??'') as string,terminalId:terminal.id,items:[{productId:product.id,quantity:2,modifiers:[],note:''}],discount:1,note:'INTEGRATION TEST',payments:[{method:'CASH',amount:9999,received:20000,reference:''}]};
 const [a,b]=await Promise.all([checkout(input,actor),checkout(input,actor)]);assert.equal(a.order.id,b.order.id);assert.equal(await db.order.count({where:{key:input.key}}),1);assert.equal(a.order.payments[0].change,10001);assert.equal(a.order.items[0].discount,1);
 await assert.rejects(()=>checkout({...input,discount:2},actor),/รหัสคำขอ/);
 await assert.rejects(()=>checkout({...input,key:randomUUID()}, {...actor,role:'CASHIER'}),/สิทธิ์ให้ส่วนลด/);
 const before=await report(date);
 await assert.rejects(()=>checkout({...input,key:randomUUID(),payments:[{method:'CASH',amount:9999,received:1,reference:''}]},actor),/เงินรับ/);
 assert.equal((await report(date)).summary.total,before.summary.total);
 await db.product.update({where:{id:product.id},data:{price:9900,name:'CHANGED'}});const unchanged=await db.orderItem.findMany({where:{orderId:a.order.id}});assert.equal(unchanged[0].name,'TEST กะเพรา');assert.equal(unchanged[0].unitPrice,5000);
 await db.setting.update({where:{key:'system'},data:{value:json({...config,storeName:'Changed shop',profile:{...config.profile,paperMm:'80',width:576,characters:48}})}});
 const jobs=await reprint(a.order.id,actor);assert.equal(await db.order.count({where:{key:input.key}}),1);assert.equal(jobs[0].isReprint,true);
 const reprinted=jobs[0].payload as unknown as import('../src/lib/types').Receipt;
 assert.equal(reprinted.config.profile.paperMm,'80');assert.equal(reprinted.config.profile.width,576);assert.equal(reprinted.config.storeName,'Original shop');assert.equal(reprinted.total,a.order.total);assert.equal(reprinted.items?.[0].unitPrice,5000);
 assert.deepEqual((await db.order.findUniqueOrThrow({where:{id:a.order.id}})).receiptConfig,a.order.receiptConfig);
 const claimed=await claimJob(jobs[0].id,actor);assert.ok(claimed.claimToken);await assert.rejects(()=>claimJob(jobs[0].id,actor),/ถูกส่งพิมพ์แล้ว/);await db.printJob.update({where:{id:jobs[0].id},data:{status:'FAILED',error:'paper out'}});assert.equal((await db.order.findUniqueOrThrow({where:{id:a.order.id}})).status,'COMPLETED');
 const previousTotal=(await report(date)).summary.total;await adjustOrder(a.order.id,'REFUND',3000,'test partial refund','CASH',actor);const afterRefund=await report(date);assert.equal(afterRefund.summary.total,previousTotal-3000);assert.equal(afterRefund.summary.categories.reduce((s,c)=>s+c.total,0),afterRefund.summary.total);assert.equal(Object.values(afterRefund.summary.payments).reduce((s,v)=>s+v,0),afterRefund.summary.total);
 await assert.rejects(()=>adjustOrder(a.order.id,'REFUND',9999,'over refund','CASH',actor),/เกินยอด/);
 const remaining=6999;const results=await Promise.allSettled([adjustOrder(a.order.id,'REFUND',remaining,'concurrent refund 1','CASH',actor),adjustOrder(a.order.id,'REFUND',remaining,'concurrent refund 2','CASH',actor)]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);
 const secondInput={...input,key:randomUUID(),discount:0,items:[{...input.items[0],quantity:1}],payments:[{method:'CASH' as const,amount:9900,received:9900,reference:''}]};const second=await checkout(secondInput,actor);await adjustOrder(second.order.id,'VOID',0,'test void','CASH',actor);await assert.rejects(()=>adjustOrder(second.order.id,'VOID',0,'double void','CASH',actor));
 const totals=await report(date);await assert.rejects(()=>closeDay(date,totals.summary.payments.CASH+1,'',actor),/เหตุผล/);const closed=await closeDay(date,totals.summary.payments.CASH,'integration close',actor);assert.equal(closed.difference,0);await assert.rejects(()=>checkout({...secondInput,key:randomUUID()},actor),/ปิดยอดแล้ว/);await assert.rejects(()=>adjustOrder(a.order.id,'REFUND',1,'closed day','CASH',actor),/ปิดยอดแล้ว/);await reopenDay(date,'integration reopen',actor);
 const audit=await db.auditLog.findFirstOrThrow({where:{userId:user.id}});await assert.rejects(()=>db.auditLog.delete({where:{id:audit.id}}));await assert.rejects(()=>db.orderItem.update({where:{id:unchanged[0].id},data:{name:'tampered'}}));await assert.rejects(()=>db.payment.deleteMany({where:{orderId:a.order.id}}));
 await db.product.update({where:{id:product.id},data:{active:false}});await db.category.update({where:{id:category.id},data:{active:false}});await db.terminal.update({where:{id:terminal.id},data:{active:false}});await db.user.update({where:{id:user.id},data:{active:false}});
 const historicalDate=new Date(Date.UTC(1990,0,1)+(parseInt(suffix,16)%10000)*86400000).toISOString().slice(0,10);
 await db.businessDay.create({data:{date:historicalDate,config:json({...defaultSettings,cutoff1:'10:00',cutoff2:'14:00'})}});
 const historical=[];
 for(const [time,value] of [['09:59:59',100],['10:00:00',200],['14:00:00',300]] as const){historical.push(await db.order.create({data:{key:randomUUID(),requestHash:'fixture',number:`TEST-${suffix}-${time}`,queue:`TEST-${time}`,businessDate:historicalDate,cashierId:actor.id,terminalId:terminal.id,subtotal:value,discount:0,total:value,createdAt:new Date(`${historicalDate}T${time}+07:00`),receiptConfig:json(defaultSettings),items:{create:{productId:product.id,name:'TEST boundary',categoryId:category.id,categoryName:'TEST category',unitPrice:value,quantity:1,discount:0,lineTotal:value,modifiers:[]}},payments:{create:{method:'CASH',amount:value,received:value,change:0}}}}));}
 const historicalReport=await report(historicalDate);assert.equal(historicalReport.summary.total,600);assert.equal('periods' in historicalReport.summary,false);assert.equal('cutoff1' in historicalReport.config,false);
 const legacyOrder=await db.order.findUniqueOrThrow({where:{id:historical[0].id},include:{items:true,payments:true,adjustments:true}});
 const first=await db.salesSnapshot.create({data:{businessDate:historicalDate,cutoff:'10:00',summary:json(summarize([legacyOrder])),userId:actor.id}});
 await adjustOrder(historical[0].id,'REFUND',50,'historical test refund','CASH',actor);assert.equal((await report(historicalDate)).summary.total,550);assert.equal(((await db.salesSnapshot.findUniqueOrThrow({where:{id:first.id}})).summary as {total:number}).total,100);await assert.rejects(()=>db.salesSnapshot.update({where:{id:first.id},data:{cutoff:'11:00'}}));
 const trend=await salesTrend(historicalDate,7);assert.equal(trend.length,7);assert.equal(trend.at(-1)?.date,historicalDate);assert.equal(trend.at(-1)?.total,550);assert.equal(trend.at(-1)?.count,3);assert.ok(trend.slice(0,-1).every(day=>day.total===0&&day.count===0));
 const historicalClose=await closeDay(historicalDate,500,'50 satang short',actor);assert.equal(historicalClose.difference,-50);await assert.rejects(()=>db.dailyClosing.delete({where:{id:historicalClose.id}}));await reopenDay(historicalDate,'new correction revision',actor);await closeDay(historicalDate,550,'reconciled',actor);assert.equal(await db.dailyClosing.count({where:{businessDate:historicalDate}}),2);
 await db.terminal.update({where:{id:terminal.id},data:{active:true}});
 const orderCount=await db.order.count(),closingCount=await db.dailyClosing.count();
 const dailyJob=await dailyReportPrint(historicalDate,terminal.id,{...actor,role:'CASHIER'});
 assert.equal(dailyJob.orderId,null);assert.equal(dailyJob.template,'DAILY_REPORT');
 const payload=dailyJob.payload as unknown as import('../src/lib/types').Receipt;
 assert.equal(payload.dailyReport?.summary.total,550);assert.equal(payload.dailyReport?.businessDate,historicalDate);assert.equal(payload.dailyReport?.closed,true);
 assert.equal(payload.config.profile.paperMm,'80');assert.equal(payload.config.profile.width,576);assert.equal(payload.config.profile.bitmapThai,true);
 assert.equal(payload.payments,undefined);assert.equal(await db.order.count(),orderCount);assert.equal(await db.dailyClosing.count(),closingCount);
 await claimJob(dailyJob.id,actor);await assert.rejects(()=>claimJob(dailyJob.id,actor),/ถูกส่งพิมพ์แล้ว/);
 await assert.rejects(()=>dailyReportPrint(historicalDate,terminal.id,{...actor,role:'VIEWER'}),/สิทธิ์/);
 await db.terminal.update({where:{id:terminal.id},data:{config:{printerId:'mock',adapter:'browser'}}});
 const laptopJob=await dailyReportPrint(historicalDate,terminal.id,actor);assert.equal(laptopJob.template,'DAILY_REPORT');
 await db.terminal.update({where:{id:terminal.id},data:{active:false}});
 await assert.rejects(()=>dailyReportPrint(historicalDate,terminal.id,actor),/เปิดใช้งาน/);
 const resetPassword=randomUUID();await db.user.update({where:{id:actor.id},data:{active:true,passwordHash:await passwordHash(resetPassword,12)}});
 await assert.rejects(()=>resetPreview({...actor,role:'ADMIN'}),/Super Admin/);
 let resetInfo=await resetPreview(actor);
 await assert.rejects(()=>resetSales({password:resetPassword,reason:'integration reset',confirmation:'RESET ALL SALES',token:resetInfo.token},actor),/กำลังพิมพ์/);
 await db.printJob.updateMany({where:{status:'PRINTING'},data:{status:'FAILED'}});
 resetInfo=await resetPreview(actor);
 await assert.rejects(()=>resetSales({password:'wrong',reason:'integration reset',confirmation:'RESET ALL SALES',token:resetInfo.token},actor),/รหัสผ่าน/);
 await assert.rejects(()=>resetSales({password:resetPassword,reason:'integration reset',confirmation:'RESET ALL SALES',token:'stale'},actor),/ข้อมูลขายเปลี่ยน/);
 const productsBefore=await db.product.count(),usersBefore=await db.user.count(),counterBefore=(await db.businessDay.findUniqueOrThrow({where:{date}})).counter;
 const resetResult=await resetSales({password:resetPassword,reason:'integration reset',confirmation:'RESET ALL SALES',token:resetInfo.token},actor);
 const archive=await resetArchive(resetResult.id,actor) as {orders:{id:string}[];payments:unknown[];closings:unknown[];staff:{passwordHash?:string}[]};
 assert.ok(archive.orders.some(o=>o.id===a.order.id));assert.equal(archive.orders.length,resetInfo.counts.orders);assert.equal(archive.payments.length,resetInfo.counts.payments);assert.equal(archive.closings.length,resetInfo.counts.closings);assert.ok(archive.staff.every(s=>!s.passwordHash));
 assert.equal((await resetPreview(actor)).counts.orders,0);assert.equal(await db.order.count(),0);assert.equal(await db.payment.count(),0);assert.equal((await report(date)).summary.total,0);assert.equal(await db.product.count(),productsBefore);assert.equal(await db.user.count(),usersBefore);
 assert.equal((await db.businessDay.findUniqueOrThrow({where:{date}})).counter,counterBefore);assert.equal((await db.businessDay.findUniqueOrThrow({where:{date:historicalDate}})).closed,false);
 assert.ok((await resetArchives(actor)).some(r=>r.id===resetResult.id));await assert.rejects(()=>db.$executeRaw`DELETE FROM "SalesResetArchive" WHERE id=${resetResult.id}`);
 await assert.rejects(()=>checkout({...input,salesVersion:resetResult.salesVersion},actor),/ถูกเก็บในการรีเซ็ต/);
 await assert.rejects(()=>checkout({...input,key:randomUUID()},actor),/รีเซ็ตแล้ว/);
 await db.terminal.update({where:{id:terminal.id},data:{active:true}});await db.product.update({where:{id:product.id},data:{active:true}});await db.category.update({where:{id:category.id},data:{active:true}});
 const fresh=await checkout({...secondInput,key:randomUUID(),salesVersion:resetResult.salesVersion},actor);assert.equal(fresh.order.total,9900);assert.notEqual(fresh.order.queue,a.order.queue);
 await db.user.update({where:{id:actor.id},data:{active:false}});await db.product.update({where:{id:product.id},data:{active:false}});await db.terminal.update({where:{id:terminal.id},data:{active:false}});await db.category.update({where:{id:category.id},data:{active:false}});
});

test('spreadsheet menu replacement removes demo rows, preserves history and is idempotent',{skip:!enabled},async()=>{
 await seedMenu(db);
 const suffix=randomUUID(),legacyCategory=await db.category.create({data:{id:'category-1',name:'อาหารตามสั่ง',shortcut:'F1'}});
 const legacy=await db.product.create({data:{sku:'DEMO-001',name:'ข้าวกะเพราไก่',price:5000,categoryId:legacyCategory.id,modifiers:{create:{name:'พิเศษ',price:1000}}},include:{modifiers:true}});
 await db.category.upsert({where:{id:'category-3'},create:{id:'category-3',name:'ไอศกรีม',shortcut:'F3'},update:{active:true}});
 const custom=await db.product.create({data:{sku:`TEST-CUSTOM-${suffix}`,name:'Custom archived menu',price:1250,active:false,categoryId:'category-3'}});
 const user=await db.user.create({data:{username:`menu-test-${suffix}`,name:'MENU TEST',passwordHash:'not-a-login'}});
 const terminal=await db.terminal.create({data:{id:`MENU-TEST-${suffix}`,name:'MENU TEST',config:{adapter:'mock'}}});
 const history=await db.order.create({data:{key:randomUUID(),requestHash:'fixture',number:`MENU-TEST-${suffix}`,queue:'MENU TEST',businessDate:'1999-12-31',cashierId:user.id,terminalId:terminal.id,subtotal:5000,discount:0,total:5000,receiptConfig:json(defaultSettings),items:{create:{productId:legacy.id,name:legacy.name,categoryId:legacyCategory.id,categoryName:legacyCategory.name,unitPrice:5000,quantity:1,discount:0,lineTotal:5000,modifiers:[]}},payments:{create:{method:'CASH',amount:5000,received:5000,change:0}}},include:{items:true,payments:true}});
 const result=await seedMenu(db);
 assert.equal(result.menuItems,91);assert.equal(result.removedProducts,1);assert.equal(result.removedModifiers,1);assert.ok(result.backup);
 assert.equal(await db.product.findUnique({where:{id:legacy.id}}),null);
 assert.equal(await db.modifier.findUnique({where:{id:legacy.modifiers[0].id}}),null);
 assert.equal(await db.category.findUnique({where:{id:legacyCategory.id}}),null);
 assert.equal((await db.category.findUniqueOrThrow({where:{id:'category-3'}})).active,false);
 assert.equal((await db.product.findUniqueOrThrow({where:{id:custom.id}})).price,1250);
 assert.deepEqual(await db.order.findUniqueOrThrow({where:{id:history.id},include:{items:true,payments:true}}),history);
 for(const category of menuData.categories){
  const products=await db.product.findMany({where:{sku:{in:category.products.map(p=>p.sku)}}});
  assert.equal(products.length,category.products.length);
  for(const expected of category.products){const actual=products.find(p=>p.sku===expected.sku)!;assert.equal(actual.name,expected.name);assert.equal(actual.price,expected.price);assert.equal(actual.categoryId,category.id);}
 }
 const first=menuData.categories[0].products[0];
 await db.product.update({where:{sku:first.sku},data:{price:9900}});
 const audits=await db.auditLog.count({where:{action:'MENU_SEED_REPLACE'}});
 const again=await seedMenu(db);assert.equal(again.createdProducts,0);assert.equal(again.removedProducts,0);assert.equal(again.backup,null);
 assert.equal(await db.auditLog.count({where:{action:'MENU_SEED_REPLACE'}}),audits);
 assert.equal((await db.product.findUniqueOrThrow({where:{sku:first.sku}})).price,9900);
 await db.product.update({where:{sku:first.sku},data:{price:first.price}});
 await db.product.delete({where:{id:custom.id}});
 await db.user.update({where:{id:user.id},data:{active:false}});
 await db.terminal.update({where:{id:terminal.id},data:{active:false}});
});
