import {money} from '@/lib/domain';
import {thaiDate} from '@/lib/client';
import {reportDate,type SalesReport} from '@/lib/reporting';

export default function A4SalesReport({report,title,preparedBy,filters}:{report:SalesReport;title:string;preparedBy:string;filters:string[]}){
 const s=report.summary;
 const period=report.from===report.to?reportDate(report.from):`${reportDate(report.from)} – ${reportDate(report.to)}`;
 return <article className="a4-sales-report" aria-label="รายงานยอดขายสำหรับพิมพ์ A4">
  <header className="a4-report-header"><div><p>{report.config.organization}</p><h1>{title}</h1><span>{report.config.storeName}</span></div><div className="a4-report-period"><strong>{period}</strong><span>หน่วยเงิน: บาท</span><span>{report.from===report.to?`วันทำการเริ่ม ${report.config.opening} น.`:'สรุปตามวันทำการของแต่ละวัน'}</span></div></header>
  <div className="a4-report-meta"><p><strong>ขอบเขตข้อมูล:</strong> {filters.length?filters.join(' / '):'ทุกหมวดสินค้า ทุกพนักงาน และทุกเครื่อง POS'}</p><p>จัดทำโดย {preparedBy} / ข้อมูล ณ {thaiDate(report.generatedAt)}</p></div>
  <div className="a4-kpis"><div><span>ยอดขายสุทธิ</span><strong>{money(s.total)}</strong></div><div><span>จำนวนบิลที่ไม่ยกเลิก</span><strong>{s.count.toLocaleString()}</strong></div><div><span>สินค้าที่ขาย (ชิ้น)</span><strong>{s.quantity.toLocaleString()}</strong></div><div><span>เฉลี่ยต่อบิล</span><strong>{money(s.average)}</strong></div></div>
  <section><h2>ยอดขายแยกตามหมวดสินค้า</h2><table className="a4-category-table"><thead><tr><th>ลำดับ</th><th>หมวดสินค้า</th><th className="number">จำนวนชิ้น</th><th className="number">ส่วนลด</th><th className="number">ยอดสุทธิ</th><th className="number">สัดส่วน</th></tr></thead><tbody>{s.categories.map((c,i)=><tr key={c.id}><td>{i+1}</td><td>{c.name}</td><td className="number">{c.quantity.toLocaleString()}</td><td className="number">{money(c.discount)}</td><td className="number">{money(c.total)}</td><td className="number">{s.total?(c.total/s.total*100).toFixed(1):'0.0'}%</td></tr>)}{!s.categories.length&&<tr><td colSpan={6}>ไม่มีรายการขายในช่วงที่เลือก</td></tr>}</tbody><tfoot><tr><th colSpan={2}>รวมทั้งหมด</th><th className="number">{s.quantity.toLocaleString()}</th><th className="number">{money(s.categories.reduce((sum,c)=>sum+c.discount,0))}</th><th className="number">{money(s.total)}</th><th className="number">{s.total?'100.0':'0.0'}%</th></tr></tfoot></table></section>
  <div className="a4-two-columns"><section><h2>ยอดตามวิธีชำระเงิน</h2>{report.filters?<p className="a4-note">ไม่แสดงยอดชำระเมื่อเลือกเฉพาะหมวดหรือสินค้า เพราะบิลเดียวอาจมีสินค้าหลายหมวด</p>:<table><tbody>{[['CASH','เงินสด'],['QR','QR / โอน'],['OTHER','อื่น ๆ']].map(([method,label])=><tr key={method}><td>{label}</td><td className="number">{money(s.payments[method]??0)}</td></tr>)}</tbody><tfoot><tr><th>รวมยอดรับสุทธิ</th><th className="number">{money(Object.values(s.payments).reduce((sum,value)=>sum+value,0))}</th></tr></tfoot></table>}</section><section><h2>ส่วนลดและการปรับยอด</h2><table><tbody>{[['ส่วนลด',s.discount],['ยอดบิลยกเลิก',s.voided],['คืนเงิน',s.refunded]].map(([label,value])=><tr key={label}><td>{label}</td><td className="number">{money(Number(value))}</td></tr>)}</tbody></table><p className="a4-note">ยอดสุทธิหักส่วนลดและคืนเงินแล้ว และไม่รวมบิลยกเลิก</p></section></div>
  {s.products.length>0&&<section><h2>สินค้าขายดี 10 อันดับ (ตามยอดสุทธิ)</h2><table><thead><tr><th>อันดับ</th><th>สินค้า</th><th className="number">จำนวนชิ้น</th><th className="number">ยอดสุทธิ</th></tr></thead><tbody>{s.products.slice(0,10).map((p,i)=><tr key={`${i}-${p.name}`}><td>{i+1}</td><td>{p.name}</td><td className="number">{p.quantity.toLocaleString()}</td><td className="number">{money(p.total)}</td></tr>)}</tbody></table></section>}
  <footer className="a4-report-footer"><p>จำนวนชิ้นเป็นยอดขายก่อนหักจำนวนคืน เงินสดไม่รวมเงินตั้งต้น</p><div className="a4-signatures"><div><span>{preparedBy}</span><p>ผู้จัดทำรายงาน</p></div><div><span>&nbsp;</span><p>ผู้ตรวจสอบ</p></div><div><span>&nbsp;</span><p>ผู้รับเงิน</p></div></div></footer>
 </article>;
}
