'use client';
import {useState,useEffect,useCallback} from 'react';
import {Search,Printer,Eye,Ban,RotateCcw} from 'lucide-react';
import {api,deviceId,thaiDate} from '@/lib/client';
import {money,businessDate,toSatang} from '@/lib/domain';
import {can} from '@/lib/permissions';
import type {Actor} from '@/lib/auth';
import type {PrintJob,Terminal} from '@/lib/types';
import {sendPrintJob} from '@/lib/printer/service';
import {Modal,Empty,Status} from './ui';
type Order={id:string;number:string;queue:string;businessDate:string;createdAt:string;total:number;subtotal:number;discount:number;refunded:number;status:string;note:string;cashier:{name:string};terminal:{name:string};items:{id:string;name:string;quantity:number;unitPrice:number;lineTotal:number;refunded:number;modifiers:{name:string}[];note:string}[];payments:{method:string;amount:number;received:number;change:number;reference:string}[];adjustments:{id:string;type:string;amount:number;reason:string;createdAt:string}[]};
export default function OrdersManager({user}:{user:Actor}){
 const [orders,setOrders]=useState<Order[]>([]),[count,setCount]=useState(0),[page,setPage]=useState(1),[from,setFrom]=useState(businessDate()),[to,setTo]=useState(businessDate()),[search,setSearch]=useState(''),[status,setStatus]=useState(''),[method,setMethod]=useState(''),[detail,setDetail]=useState<Order|null>(null),[adjust,setAdjust]=useState<'void'|'refund'|null>(null),[amount,setAmount]=useState(''),[refundMethod,setRefundMethod]=useState('CASH'),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const params=new URLSearchParams({from,to,search,status,method,page:String(page)}).toString();const load=useCallback(async()=>{try{const data=await api<{orders:Order[];count:number}>(`orders?${params}`);setOrders(data.orders);setCount(data.count);}catch(e){setError((e as Error).message);}},[params]);useEffect(()=>{void load();},[load]);
 const reprint=async(id:string)=>{try{const catalog=await api<{terminals:Terminal[]}>('catalog'),terminal=catalog.terminals.find(t=>t.id===deviceId());if(!terminal)throw new Error('เลือกเครื่อง POS ในการตั้งค่าก่อน');const jobs=await api<PrintJob[]>(`orders/${id}/reprint`,{});for(const job of jobs)await sendPrintJob(job,terminal);setNotice('ส่งพิมพ์สำเนาแล้ว');}catch(e){setError((e as Error).message);}};
 const submit=async()=>{if(!detail||!adjust||busy)return;setBusy(true);try{await api(`orders/${detail.id}/${adjust}`,{reason,amount:adjust==='refund'?toSatang(amount):0,method:refundMethod});setDetail(await api<Order>(`orders/${detail.id}`));setAdjust(null);setNotice('บันทึกการปรับยอดแล้ว');await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 return <><div className="page-heading"><div><span className="eyebrow">TRANSACTION HISTORY</span><h1>ประวัติการขาย</h1><p>ค้นหาบิล ตรวจสอบรายละเอียด และพิมพ์สำเนา</p></div><span className="badge">{count} บิล</span></div>{error&&<div role="alert" className="error">{error}</div>}{notice&&<div role="status" className="notice">{notice}</div>}<div className="panel"><div className="table-toolbar"><label className="search-box"><Search size={17}/><input aria-label="ค้นหาบิล" placeholder="เลขบิล / ชื่อสินค้า" value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}}/></label><label>ตั้งแต่<input type="date" value={from} onChange={e=>{setFrom(e.target.value);setPage(1);}}/></label><label>ถึง<input type="date" value={to} onChange={e=>{setTo(e.target.value);setPage(1);}}/></label><select aria-label="สถานะ" value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}}><option value="">ทุกสถานะ</option>{[['COMPLETED','สำเร็จ'],['VOIDED','ยกเลิก'],['PARTIALLY_REFUNDED','คืนบางส่วน'],['REFUNDED','คืนครบ']].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><select aria-label="การชำระเงิน" value={method} onChange={e=>{setMethod(e.target.value);setPage(1);}}><option value="">ทุกการชำระ</option><option value="CASH">เงินสด</option><option value="QR">QR / โอน</option><option value="OTHER">อื่น ๆ</option></select></div><div className="table-scroll"><table><thead><tr><th>เลขบิล / เวลา</th><th>คิว</th><th>ผู้ขาย / เครื่อง</th><th>การชำระ</th><th className="number">ยอดสุทธิ</th><th>สถานะ</th><th/></tr></thead><tbody>{orders.map(o=><tr key={o.id}><td><strong>{o.number}</strong><small>{thaiDate(o.createdAt)}</small></td><td><strong>{o.queue}</strong></td><td>{o.cashier.name}<small>{o.terminal.name}</small></td><td>{o.payments.map(p=>p.method==='CASH'?'เงินสด':p.method==='QR'?'QR/โอน':'อื่น ๆ').join(' + ')}</td><td className="number emphasis">฿{money(o.total-o.refunded)}</td><td><Status value={o.status}/></td><td><button className="icon-button" title="ดูรายละเอียด" onClick={()=>{setDetail(o);setAdjust(null);}}><Eye size={18}/></button></td></tr>)}</tbody></table>{!orders.length&&<Empty text="ไม่พบบิลในช่วงที่เลือก"/>}</div><div className="pagination"><span>{count} รายการ · หน้า {page}</span><div><button className="secondary" disabled={page===1} onClick={()=>setPage(page-1)}>ก่อนหน้า</button><button className="secondary" disabled={page*30>=count} onClick={()=>setPage(page+1)}>ถัดไป</button></div></div></div>
 {detail&&<Modal title={detail.number} wide onClose={()=>{if(!busy){setDetail(null);setAdjust(null);}}}><div className="order-detail-head"><div><span className="muted">เลขคิว</span><h2>{detail.queue}</h2></div><Status value={detail.status}/><span>{thaiDate(detail.createdAt)}<small>{detail.cashier.name} · {detail.terminal.name}</small></span></div><table><thead><tr><th>สินค้า</th><th className="number">จำนวน</th><th className="number">ยอด</th></tr></thead><tbody>{detail.items.map(i=><tr key={i.id}><td>{i.name}<small>{i.modifiers.map(m=>m.name).join(' · ')} {i.note}</small></td><td className="number">{i.quantity}</td><td className="number">{money(i.lineTotal)}{i.refunded>0&&<small>คืน {money(i.refunded)}</small>}</td></tr>)}</tbody></table><div className="metric-row"><span>รวม / ส่วนลด</span><strong>{money(detail.subtotal)} / {money(detail.discount)}</strong></div><div className="metric-row"><span>ยอดชำระ / คืนแล้ว</span><strong>{money(detail.total)} / {money(detail.refunded)}</strong></div>{detail.payments.map((p,i)=><div key={i} className="metric-row"><span>{p.method} · {p.reference||'ไม่มีเลขอ้างอิง'}</span><strong>{money(p.amount)} · รับ {money(p.received)} · ทอน {money(p.change)}</strong></div>)}{detail.note&&<p>หมายเหตุ: {detail.note}</p>}{detail.adjustments.map(a=><div key={a.id} className="info">{a.type} ฿{money(a.amount)} · {a.reason} · {thaiDate(a.createdAt)}</div>)}<div className="modal-actions">{can(user.role,'sell')&&<button className="secondary" onClick={()=>void reprint(detail.id)}><Printer size={16}/>พิมพ์ซ้ำ</button>}{can(user.role,'void')&&detail.status==='COMPLETED'&&<button className="secondary danger-text" onClick={()=>{setAdjust('void');setReason('');}}><Ban size={16}/>ยกเลิกบิล</button>}{can(user.role,'refund')&&['COMPLETED','PARTIALLY_REFUNDED'].includes(detail.status)&&<button className="secondary" onClick={()=>{setAdjust('refund');setReason('');setAmount(((detail.total-detail.refunded)/100).toFixed(2));setRefundMethod(detail.payments[0]?.method??'CASH');}}><RotateCcw size={16}/>คืนเงิน</button>}</div>{adjust&&<div className="adjust-form"><h3>{adjust==='void'?'ยืนยันยกเลิกบิล':'คืนเงิน'}</h3>{adjust==='refund'&&<div className="form-grid"><label>จำนวนเงิน (บาท)<input type="number" min="0.01" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label>คืนผ่าน<select value={refundMethod} onChange={e=>setRefundMethod(e.target.value)}>{[...new Set(detail.payments.map(p=>p.method))].map(m=><option key={m}>{m}</option>)}</select></label></div>}<label>เหตุผล (จำเป็น)<textarea value={reason} onChange={e=>setReason(e.target.value)}/></label><p className="muted small">ยอดคืนจะจัดสรรตามสัดส่วนยอดสินค้า เก็บบิลเดิมและประวัติการอนุมัติไว้</p>{error&&<div className="error">{error}</div>}<button className="primary wide" disabled={busy||reason.trim().length<3} onClick={()=>void submit()}>ยืนยัน{adjust==='void'?'ยกเลิก':'คืนเงิน'}</button></div>}</Modal>}</>;
}
