'use client';
import {useEffect,useState,useRef,useCallback} from 'react';
import Link from 'next/link';
import {Store,Search,Star,Plus,Minus,Trash2,Pause,ArrowRight,LogOut,Maximize,LayoutDashboard,ShoppingBag,Printer,Clock,CheckCircle2,History,SlidersHorizontal,ChevronRight} from 'lucide-react';
import {api,deviceId,thaiDate,uuid,ApiError} from '@/lib/client';
import {money,toSatang} from '@/lib/domain';
import {can} from '@/lib/permissions';
import type {Catalog,CartLine,Product,PrintJob,Terminal} from '@/lib/types';
import type {Checkout} from '@/lib/validation';
import {printerFor,sendPrintJob} from '@/lib/printer/service';
import {CategoryIcon,Modal,Empty,Status} from './ui';
import PosTools from './pos-tools';
type Stored={cart:CartLine[];discount:string;note:string;pending?:Checkout};
export default function Pos({userId}:{userId:string}){
 const [catalog,setCatalog]=useState<Catalog|null>(null),[cart,setCart]=useState<CartLine[]>([]),[category,setCategory]=useState('all'),[search,setSearch]=useState(''),[discount,setDiscount]=useState('0'),[note,setNote]=useState(''),[terminalId,setTerminalId]=useState('POS-01'),[online,setOnline]=useState(false),[printerStatus,setPrinterStatus]=useState('ตรวจสอบเครื่องพิมพ์'),[time,setTime]=useState(''),[modal,setModal]=useState<'payment'|'parked'|'recent'|'edit'|null>(null),[editing,setEditing]=useState<number>(0),[method,setMethod]=useState('CASH'),[received,setReceived]=useState(''),[reference,setReference]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[jobs,setJobs]=useState<PrintJob[]>([]),[parked,setParked]=useState<{id:string;label:string;cart:CartLine[];createdAt:string}[]>([]),[recent,setRecent]=useState<{id:string;number:string;queue:string;total:number;status:string}[]>([]),[loaded,setLoaded]=useState(''),[pending,setPending]=useState<Checkout|undefined>();
 const busyRef=useRef(false),searchRef=useRef<HTMLInputElement>(null);
 const terminal=catalog?.terminals.find(t=>t.id===terminalId);
 const storageKey=catalog?`cida-cart-${catalog.user.id}-${terminalId}${catalog.salesVersion?'-'+catalog.salesVersion:''}`:'';
 useEffect(()=>{setTerminalId(deviceId());const cache=localStorage.getItem('cida-catalog');if(cache)try{const cached=JSON.parse(cache);if(cached.user?.id===userId)setCatalog(cached);}catch{}api<Catalog>('catalog').then(data=>{setCatalog(data);localStorage.setItem('cida-catalog',JSON.stringify(data));setOnline(true);}).catch(e=>setError(e.message));},[]);
 useEffect(()=>{if(!storageKey)return;setLoaded('');try{const data=JSON.parse(localStorage.getItem(storageKey)??'null') as Stored|null;setCart(data?.cart??[]);setDiscount(data?.discount??'0');setNote(data?.note??'');setPending(data?.pending);}catch{setCart([]);}setLoaded(storageKey);},[storageKey]);
 useEffect(()=>{if(loaded===storageKey&&storageKey)localStorage.setItem(storageKey,JSON.stringify({cart,discount,note,pending}));},[cart,discount,note,pending,loaded,storageKey]);
 const refreshJobs=useCallback(()=>{if(terminalId)api<PrintJob[]>(`print-jobs?terminal=${encodeURIComponent(terminalId)}`).then(setJobs).catch(()=>{});},[terminalId]);
 useEffect(()=>{const tick=()=>setTime(new Intl.DateTimeFormat('th-TH',{timeZone:'Asia/Bangkok',hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(new Date()));tick();const timer=setInterval(tick,1000);return()=>clearInterval(timer);},[]);
 useEffect(()=>{if(!terminal)return;const check=()=>{api('health').then(()=>setOnline(true)).catch(()=>setOnline(false));printerFor(terminal).status().then(setPrinterStatus).catch(e=>setPrinterStatus(e.message));refreshJobs();};check();const timer=setInterval(check,15000);return()=>clearInterval(timer);},[terminal,refreshJobs]);
 useEffect(()=>{const timer=setInterval(()=>{if(!busyRef.current)api<Catalog>('catalog').then(data=>{setCatalog(data);localStorage.setItem('cida-catalog',JSON.stringify(data));}).catch(()=>{});},60000);return()=>clearInterval(timer);},[]);
 const productFor=(line:CartLine)=>catalog?.products.find(p=>p.id===line.productId);
 const linePrice=(line:CartLine)=>{const p=productFor(line);return (p?.price??0)+(p?.modifiers.filter(m=>line.modifiers.includes(m.id)).reduce((s,m)=>s+m.price,0)??0);};
 const subtotal=cart.reduce((s,line)=>s+linePrice(line)*line.quantity,0);let discountValue=0;try{discountValue=toSatang(discount);}catch{}const total=Math.max(0,subtotal-discountValue);let tender=0;try{tender=toSatang(received);}catch{}
 const updateQuantity=(index:number,value:number)=>{if(pending)return;setCart(c=>c.map((line,i)=>i===index?{...line,quantity:Math.min(999,Math.max(0,value))}:line).filter(l=>l.quantity>0));};
 const addProduct=(p:Product)=>{if(pending||busy)return;setCart(c=>{const existing=c.findIndex(l=>l.productId===p.id&&!l.modifiers.length&&!l.note);return existing>=0?c.map((l,i)=>i===existing?{...l,quantity:Math.min(999,l.quantity+1)}:l):[...c,{productId:p.id,quantity:1,modifiers:[],note:''}];});if(terminal?.config.sound){try{const ctx=new AudioContext(),osc=ctx.createOscillator(),gain=ctx.createGain();osc.frequency.value=700;gain.gain.value=.035;osc.connect(gain);gain.connect(ctx.destination);osc.start();osc.stop(ctx.currentTime+.04);osc.onended=()=>void ctx.close();}catch{}}};
 const openPayment=()=>{if(!cart.length||pending||busy)return;setMethod('CASH');setReceived((total/100).toFixed(2));setReference('');setModal('payment');setError('');};
 const print=useCallback((newJobs:PrintJob[],device:Terminal)=>{for(const job of newJobs)sendPrintJob(job,device).then(()=>{setNotice(job.template==='DAILY_REPORT'?'ส่งรายงาน 58 มม. ไปเครื่องพิมพ์แล้ว':'ส่งใบเสร็จไปเครื่องพิมพ์แล้ว');refreshJobs();}).catch(e=>{setError(`${job.template==='DAILY_REPORT'?'พิมพ์รายงานไม่สำเร็จ':'บันทึกการขายแล้ว แต่พิมพ์ไม่สำเร็จ'}: ${e.message}`);refreshJobs();});},[refreshJobs]);
 const pay=async()=>{if(busyRef.current||!catalog||!terminal)return;busyRef.current=true;setBusy(true);setError('');try{let input=pending;if(!input){toSatang(discount);if(discountValue>subtotal)throw new Error('ส่วนลดเกินยอดสินค้า');if(method==='CASH'&&tender<total)throw new Error('เงินรับไม่เพียงพอ');input={key:uuid(),salesVersion:catalog?.salesVersion??'',terminalId,items:cart,discount:discountValue,note,payments:[{method:method as 'CASH'|'QR'|'OTHER',amount:total,received:method==='CASH'?tender:total,reference}]};setPending(input);localStorage.setItem(storageKey,JSON.stringify({cart,discount,note,pending:input}));}const result=await api<{order:{id:string;number:string;queue:string;total:number;payments:{change:number}[]};jobs:PrintJob[]}>('checkout',input);setCart([]);setDiscount('0');setNote('');setPending(undefined);localStorage.setItem(storageKey,JSON.stringify({cart:[],discount:'0',note:''}));setModal(null);setNotice(`ชำระสำเร็จ · คิว ${result.order.queue} · เงินทอน ฿${money(result.order.payments.reduce((s,p)=>s+p.change,0))}`);print(result.jobs.filter(j=>j.status==='PENDING'),terminal);refreshJobs();}catch(e){if(e instanceof ApiError&&e.status===409&&e.message.includes('รีเซ็ต')){setModal(null);api<Catalog>('catalog').then(data=>{setCatalog(data);localStorage.setItem('cida-catalog',JSON.stringify(data));refreshJobs();}).catch(()=>{});}if(e instanceof ApiError && [400,403].includes(e.status)){setPending(undefined);localStorage.setItem(storageKey,JSON.stringify({cart,discount,note}));}setError((e as Error).message);}finally{busyRef.current=false;setBusy(false);}};
 const park=async()=>{if(!cart.length||pending||busy)return;try{await api('parked',{terminalId,label:`บิลพัก ${new Intl.DateTimeFormat('th-TH',{timeStyle:'short'}).format(new Date())}`,cart});setCart([]);setDiscount('0');setNote('');setNotice('พักบิลแล้ว');}catch(e){setError((e as Error).message);}};
 const showParked=async()=>{try{setParked(await api('parked'));setModal('parked');}catch(e){setError((e as Error).message);}};
 const showRecent=async()=>{try{const data=await api<{orders:typeof recent}>('orders');setRecent(data.orders);setModal('recent');}catch(e){setError((e as Error).message);}};
 useEffect(()=>{const handler=(e:KeyboardEvent)=>{if(e.key==='Escape'){if(!busyRef.current)setModal(null);return;}if((e.target as HTMLElement).closest('dialog')&&!modal)return;if(modal){if(e.key==='Enter'&&modal==='payment'&&(e.target as HTMLElement).tagName!=='TEXTAREA'){e.preventDefault();void pay();}return;}if(e.key==='F8'){e.preventDefault();void park();}else if(e.key==='F9'){e.preventDefault();openPayment();}else if(e.key==='/'&&(e.target as HTMLElement).tagName!=='INPUT'){e.preventDefault();searchRef.current?.focus();}else{const cat=catalog?.categories.find(c=>c.shortcut===e.key);if(cat){e.preventDefault();setCategory(cat.id);}}};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler);});
 const products=catalog?.products.filter(p=>(category==='all'||category==='favorites'&&p.favorite||p.categoryId===category)&&(!search||`${p.name} ${p.sku} ${p.barcode??''}`.toLowerCase().includes(search.toLowerCase())))??[];
 const selectedCategory=catalog?.categories.find(c=>c.id===category);
 const run=async(fn:()=>Promise<unknown>)=>{try{await fn();}catch(e){setError((e as Error).message);}};
 return <main className={terminal?.config.density==='compact'?'pos-shell compact':'pos-shell'}><header className="pos-header"><Link className="brand" href="/pos"><span className="brand-icon"><Store size={21}/></span>CIDA<span>POS</span></Link><div className="institution"><strong>{catalog?.config.organization??'ทัณฑสถานบำบัดพิเศษกลาง'}</strong><small>ระบบจำหน่ายสินค้าและอาหาร</small></div><div className="header-status system-status"><span className={online?'dot good':'dot bad'}/>{online?'ระบบพร้อม':'ขาดการเชื่อมต่อ'}</div><div className="header-status printer-status" title={printerStatus}><Printer size={15}/>{printerStatus}</div><button className="icon-button fullscreen-button" title="เต็มหน้าจอ" onClick={()=>{if(document.fullscreenElement)void document.exitFullscreen();else void document.documentElement.requestFullscreen().catch(()=>{});}}><Maximize size={18}/></button>{catalog&&can(catalog.user.role,'reports.read')&&<Link href="/admin/dashboard" className="header-link" aria-label="หลังบ้าน"><LayoutDashboard size={17}/><span>หลังบ้าน</span></Link>}<span className="cashier-avatar">{catalog?.user.name.slice(0,1)??'พ'}</span><span className="cashier-name">{catalog?.user.name}<small>{time} · {terminalId}</small></span><button className="icon-button" title="ออกจากระบบ" onClick={()=>void run(async()=>{await api('logout',{});localStorage.removeItem('cida-catalog');window.location.href='/login';})}><LogOut size={18}/></button></header>
 <div className="pos-body"><aside className="category-sidebar"><span className="eyebrow">หมวดสินค้า</span><button className={`category-button category-all ${category==='all'?'selected':''}`} aria-pressed={category==='all'} onClick={()=>setCategory('all')}><ShoppingBag size={21}/><span>ทั้งหมด<small>สินค้าทุกหมวด</small></span></button><button className={`category-button category-favorites ${category==='favorites'?'selected':''}`} aria-pressed={category==='favorites'} onClick={()=>setCategory('favorites')}><Star size={21}/><span>เมนูขายดี<small>รายการโปรด</small></span></button><div className="sidebar-divider"/>{catalog?.categories.map(c=><button key={c.id} data-tone={catalog.categories.indexOf(c)%5} className={`category-button ${category===c.id?'selected':''}`} aria-pressed={category===c.id} onClick={()=>setCategory(c.id)} style={{'--category-color':c.color} as React.CSSProperties}><CategoryIcon name={c.icon}/><span>{c.name}<small>{c.shortcut||'เลือกหมวด'}</small></span></button>)}<div className="sidebar-bottom"><button onClick={()=>void showParked()}><Pause size={18}/>บิลที่พักไว้</button><button onClick={()=>void showRecent()}><History size={18}/>บิลล่าสุด</button><small>F8 พักบิล · F9 ชำระเงิน</small></div></aside>
 <section className="products-panel"><div className="product-toolbar"><div><span className="eyebrow">หน้าขายสินค้า</span><h1>{selectedCategory?.name??(category==='favorites'?'เมนูขายดี':'เลือกสินค้า')}</h1><p>{products.length} รายการ · แตะสินค้าเพื่อเพิ่มลงบิล</p></div><label className="search-box"><Search size={19}/><input ref={searchRef} placeholder="ค้นหาสินค้า / สแกนบาร์โค้ด" value={search} onChange={e=>setSearch(e.target.value)} aria-label="ค้นหาสินค้า"/><kbd>/</kbd></label></div>
 {catalog&&<PosTools catalog={catalog} categoryId={category} disabled={!online||busy||!!pending} onCatalogUpdated={data=>{setCatalog(data);localStorage.setItem('cida-catalog',JSON.stringify(data));}}/>}
 {!catalog&&<div className="loading">กำลังโหลดสินค้าจากระบบ…</div>}<div className="product-grid">{products.map(p=>{const c=catalog?.categories.find(c=>c.id===p.categoryId),qty=cart.filter(l=>l.productId===p.id).reduce((s,l)=>s+l.quantity,0);return <button key={p.id} data-tone={(catalog?.categories.findIndex(category=>category.id===p.categoryId)??0)%5} className={`product-card ${!p.available?'unavailable':''} ${qty>0?'in-cart':''}`} disabled={!p.available||!!pending} onClick={()=>addProduct(p)} style={{'--category-color':c?.color??'#bd603b'} as React.CSSProperties}><div className="product-visual">{p.image?<img src={p.image} alt=""/>:<CategoryIcon name={c?.icon??'Utensils'} size={44}/>}<span className="product-category">{c?.name}</span>{p.favorite&&<Star className="favorite-star" size={16} fill="currentColor"/>}{qty>0&&<span className="product-count">{qty}</span>}</div><div className="product-content"><h3>{p.name}</h3><span className="availability"><i/>{p.available?'พร้อมขาย':'หมดชั่วคราว'}</span><div className="product-bottom"><strong>฿{money(p.price)}</strong><span className="add-circle"><Plus size={19}/></span></div></div></button>;})}</div>{catalog&&!products.length&&<Empty text="ไม่พบสินค้าที่ค้นหา"/>}<div className="products-footer"><span><CheckCircle2 size={14}/> บันทึกยอดเมื่อรับชำระสำเร็จ</span><span>จัดการเมนูและราคาได้ในหลังบ้าน</span></div></section>
 <aside className="cart-panel"><div className="cart-heading"><div><ShoppingBag size={20}/><h2>บิลปัจจุบัน</h2><span className="badge">{cart.reduce((s,l)=>s+l.quantity,0)} ชิ้น</span></div><button className="icon-button" aria-label="ล้างบิล" disabled={!cart.length||!!pending} onClick={()=>{if(confirm('ล้างสินค้าทั้งหมดในบิลปัจจุบัน?')){setCart([]);setDiscount('0');setNote('');}}}><Trash2 size={18}/></button></div><div className="cart-lines">{!cart.length?<div className="cart-empty"><ShoppingBag size={48}/><h3>พร้อมรับลูกค้าคนถัดไป</h3><p>เลือกหมวด แล้วแตะสินค้า<br/>รายการจะแสดงที่นี่</p></div>:cart.map((line,index)=>{const p=productFor(line);return <div className="cart-line" key={`${index}-${line.productId}`}><div className="cart-line-title"><strong>{p?.name??'สินค้านี้ถูกปิดใช้งาน'}</strong><strong>฿{money(linePrice(line)*line.quantity)}</strong></div>{line.modifiers.length>0&&<small>{p?.modifiers.filter(m=>line.modifiers.includes(m.id)).map(m=>m.name).join(' · ')}</small>}{line.note&&<small>{line.note}</small>}<div className="cart-line-controls"><div className="quantity-control"><button disabled={!!pending} aria-label={`ลด ${p?.name}`} onClick={()=>updateQuantity(index,line.quantity-1)}><Minus size={16}/></button><input aria-label={`จำนวน ${p?.name}`} type="number" min="1" max="999" disabled={!!pending} value={line.quantity} onChange={e=>updateQuantity(index,Number(e.target.value))}/><button disabled={!!pending} aria-label={`เพิ่ม ${p?.name}`} onClick={()=>updateQuantity(index,line.quantity+1)}><Plus size={16}/></button></div><button disabled={!!pending} className="text-button" onClick={()=>{setEditing(index);setModal('edit');}}><SlidersHorizontal size={15}/>ตัวเลือก / หมายเหตุ</button><button disabled={!!pending} className="icon-button" aria-label={`ลบ ${p?.name}`} onClick={()=>updateQuantity(index,0)}><Trash2 size={15}/></button></div></div>;})}</div>
 <div className="cart-summary"><label className="order-note"><input placeholder="หมายเหตุบิล (ถ้ามี)" disabled={!!pending} value={note} onChange={e=>setNote(e.target.value)}/></label><div className="summary-row"><span>ยอดรวม</span><span>฿{money(subtotal)}</span></div>{catalog&&can(catalog.user.role,'discount')&&<div className="summary-row"><span>ส่วนลด (บาท)</span><input className="discount-input" type="number" min="0" step="0.01" disabled={!!pending} value={discount} onChange={e=>setDiscount(e.target.value)}/></div>}<div className="cart-total"><span>ยอดสุทธิ</span><strong><small>฿</small>{money(total)}</strong></div><button className="primary pay-button" disabled={!cart.length||!online||!!pending||!terminal} onClick={openPayment}>ชำระเงิน<ArrowRight size={22}/></button><button className="secondary wide" disabled={!cart.length||!!pending} onClick={()=>void park()}><Pause size={17}/>พักบิล<kbd>F8</kbd></button></div></aside></div>
 <div className="pos-messages">{notice&&<div role="status" className="notice"><CheckCircle2 size={18}/>{notice}<button onClick={()=>setNotice('')}>ปิด</button></div>}{error&&<div role="alert" className="error">{error}<button onClick={()=>setError('')}>ปิด</button></div>}{pending&&<div className="error">มีคำขอชำระเงินที่ยังไม่ได้รับการยืนยัน กรุณาตรวจสอบด้วยรหัสเดิมก่อนแก้บิล<button disabled={busy||!online} onClick={()=>void pay()}>{busy?'กำลังตรวจสอบ…':'ตรวจสอบ / ส่งคำขอเดิม'}</button></div>}{jobs.length>0&&<div className="print-recovery"><Printer size={18}/><span>มี {jobs.length} งานพิมพ์ที่ยังไม่ยืนยัน</span>{jobs.slice(0,3).map(job=><button key={job.id} disabled={busy} onClick={()=>void run(async()=>{if(!terminal)return;if(job.status==='PENDING')print([job],terminal);else{if(!confirm('งานเดิมอาจพิมพ์ออกแล้ว จะพิมพ์สำเนาอีกครั้ง?'))return;const recovery=await api<PrintJob>(`print-jobs/${job.id}/recover`,{});print([recovery],terminal);}})}>{job.payload.dailyReport?`รายงาน ${job.payload.dailyReport.businessDate}`:job.payload.number??'ทดสอบ'} · {job.status==='PENDING'?'พิมพ์ตอนนี้':'พิมพ์สำเนา'}</button>)}</div>}</div>
 {modal==='payment'&&<Modal title="รับชำระเงิน" onClose={()=>{if(!busy)setModal(null);}}><div className="payment-total"><span>ยอดที่ต้องชำระ</span><strong>฿{money(total)}</strong></div><div className="payment-methods">{[['CASH','เงินสด'],['QR','QR / โอน'],['OTHER','อื่น ๆ']].map(([value,label])=><button key={value} disabled={busy||!!pending} className={method===value?'selected':''} onClick={()=>setMethod(value)}>{label}</button>)}</div>{method==='CASH'?<><label>รับเงิน (บาท)<input className="tender-input" inputMode="decimal" type="number" min="0" step="0.01" autoFocus value={received} disabled={busy||!!pending} onChange={e=>setReceived(e.target.value)}/></label><div className="quick-cash">{[20,50,100,200,500,1000].map(value=><button key={value} disabled={busy||!!pending} onClick={()=>setReceived(String(value))}>{value}</button>)}<button disabled={busy||!!pending} onClick={()=>setReceived((total/100).toFixed(2))}>พอดี</button></div><div className="change"><span>เงินทอน</span><strong>฿{money(Math.max(0,tender-total))}</strong></div></>:<><p className="info">ตรวจสอบว่าได้รับเงินแล้วก่อนยืนยัน</p><label>เลขอ้างอิงการชำระ<input value={reference} disabled={busy||!!pending} onChange={e=>setReference(e.target.value)}/></label></>}{error&&<div className="error">{error}</div>}<button className="primary wide" disabled={busy||!online||(method==='CASH'&&tender<total)||discountValue>subtotal} onClick={()=>void pay()}>{busy?'กำลังบันทึก…':pending?'ตรวจสอบการชำระเดิม':'รับชำระเงิน'}<ChevronRight size={20}/></button><p className="muted small">บันทึกยอดก่อนส่งพิมพ์ใบเสร็จ · Enter เพื่อยืนยัน</p></Modal>}
 {modal==='edit'&&cart[editing]&&<Modal title={productFor(cart[editing])?.name??'ตัวเลือกสินค้า'} onClose={()=>setModal(null)}><div className="modifier-list">{productFor(cart[editing])?.modifiers.map(m=><label key={m.id}><input type="checkbox" disabled={!!pending} checked={cart[editing].modifiers.includes(m.id)} onChange={e=>setCart(c=>c.map((l,i)=>i===editing?{...l,modifiers:e.target.checked?[...l.modifiers,m.id]:l.modifiers.filter(id=>id!==m.id)}:l))}/>{m.name}<span>+ ฿{money(m.price)}</span></label>)}</div><label>หมายเหตุ<input disabled={!!pending} value={cart[editing].note} onChange={e=>setCart(c=>c.map((l,i)=>i===editing?{...l,note:e.target.value}:l))}/></label><button className="primary wide" onClick={()=>setModal(null)}>เรียบร้อย</button></Modal>}
 {modal==='parked'&&<Modal title="บิลที่พักไว้" onClose={()=>setModal(null)}>{!parked.length&&<Empty text="ไม่มีบิลที่พักไว้"/>}{parked.map(p=><div key={p.id} className="list-row"><div><strong>{p.label}</strong><small>{thaiDate(p.createdAt)} · {p.cart.reduce((s,l)=>s+l.quantity,0)} ชิ้น</small></div><button className="secondary" disabled={!!pending} onClick={()=>void run(async()=>{if(cart.length){await api('parked',{terminalId,label:'บิลก่อนสลับ',cart});}const row=await api<{cart:CartLine[]}>(`parked/${p.id}`,{});setCart(row.cart);setDiscount('0');setNote('');setModal(null);})}>เรียกบิล</button></div>)}</Modal>}
 {modal==='recent'&&<Modal title="บิลล่าสุด" wide onClose={()=>setModal(null)}>{!recent.length&&<Empty text="ยังไม่มีบิล"/>}{recent.map(order=><div key={order.id} className="list-row"><div><strong>{order.number}</strong><small>คิว {order.queue} · ฿{money(order.total)}</small></div><Status value={order.status}/><button className="secondary" onClick={()=>void run(async()=>{if(!terminal)return;const newJobs=await api<PrintJob[]>(`orders/${order.id}/reprint`,{});print(newJobs,terminal);})}><Printer size={16}/>พิมพ์ซ้ำ</button></div>)}</Modal>}
 </main>;
}
