'use client';
import {useState,useEffect,useCallback,useRef} from 'react';
import {createPortal} from 'react-dom';
import {Download,RefreshCw,Printer,TrendingUp,ReceiptText,ShoppingBag,Wallet,LockKeyhole,UnlockKeyhole} from 'lucide-react';
import {api,thaiDate,deviceId} from '@/lib/client';
import {businessDate,money} from '@/lib/domain';
import {reportDate,type SalesReport} from '@/lib/reporting';
import type {Actor} from '@/lib/auth';
import type {Catalog,PrintJob} from '@/lib/types';
import {sendPrintJob} from '@/lib/printer/service';
import {can} from '@/lib/permissions';
import {Empty} from './ui';
import DashboardCharts from './dashboard-charts';
import A4SalesReport from './a4-sales-report';
const colors=['#bc603d','#557e9c','#7b9162','#b38498','#d6aa56'];
export default function Reports({section,user,context='admin'}:{section:string;user:Actor;context?:'admin'|'pos'}){
 const [printing,setPrinting]=useState(false),printingRef=useRef(false);
 async function printDaily(){
  if(printingRef.current||loading||!data||data.date!==date)return;printingRef.current=true;setPrinting(true);setError('');setNotice('');
  let saved=false;
  try{
   const devices=await api<Catalog>('catalog'),terminal=devices.terminals.find(t=>t.id===deviceId());
   if(!terminal)throw new Error('กรุณาตั้งค่าเครื่อง POS และเครื่องพิมพ์ก่อนพิมพ์รายงาน');
   const job=await api<PrintJob>('daily-report-print',{date,terminalId:terminal.id});saved=true;
   await sendPrintJob(job,terminal);
   setNotice(terminal.config.adapter==='mock'?`ทดสอบรายงาน ${job.profile.paperMm} มม. แล้ว (เครื่องพิมพ์จำลอง)`:`ส่งรายงาน ${job.profile.paperMm} มม. ไปเครื่องพิมพ์แล้ว`);
  }catch(error){setError(`${(error as Error).message}${saved?' · รายงานอาจพิมพ์ออกแล้ว กรุณาตรวจสอบกระดาษ หากต้องพิมพ์อีกครั้งให้ปิดหน้าต่างนี้และใช้งานพิมพ์ที่ยังไม่ยืนยันบนหน้าขาย':''}`);}
  finally{printingRef.current=false;setPrinting(false);}
 }
 const [date,setDate]=useState(businessDate()),[from,setFrom]=useState(businessDate()),[to,setTo]=useState(businessDate()),[data,setData]=useState<SalesReport|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[trendDays,setTrendDays]=useState<7|30>(7),[actual,setActual]=useState(''),[note,setNote]=useState(''),[filter,setFilter]=useState({category:'',product:'',cashier:'',terminal:'',method:'',status:''}),[catalog,setCatalog]=useState<{categories:{id:string;name:string;color:string}[];products:{id:string;name:string}[];config:Catalog['config']}|null>(null);
 const requestVersion=useRef(0);
 const [loadedParams,setLoadedParams]=useState('');
 const params=new URLSearchParams({date,...(section==='dashboard'?{trend:String(trendDays)}:{}),...(section==='reports'?{from,to,...Object.fromEntries(Object.entries(filter).filter(([,v])=>v))}:{})}).toString();
 const load=useCallback(async()=>{const version=++requestVersion.current;setLoading(true);try{const next=await api<SalesReport>(`reports?${params}`);if(version===requestVersion.current){setData(next);setLoadedParams(params);setError('');}}catch(e){if(version===requestVersion.current)setError((e as Error).message);}finally{if(version===requestVersion.current)setLoading(false);}},[params]);
 useEffect(()=>{setData(null);void load();return()=>{requestVersion.current++;};},[load]);
 useEffect(()=>{api<typeof catalog>('catalog').then(setCatalog).catch(()=>{});},[]);
 useEffect(()=>{if(section!=='dashboard')return;const timer=setInterval(()=>void load(),30000);return()=>clearInterval(timer);},[load,section]);
 const run=async(fn:()=>Promise<unknown>,success:string)=>{if(busy)return;setBusy(true);setError('');try{await fn();setNotice(success);await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 const s=data?.summary;
 const title=({dashboard:'ภาพรวมการขาย',daily:'รายงานประจำวัน',reports:'รายงานยอดขาย',closings:'ปิดยอดประจำวัน'} as Record<string,string>)[section];
 const categoryColors=Object.fromEntries(data?.summary.categories.map((c,i)=>[c.id,catalog?.categories.find(category=>category.id===c.id)?.color??colors[i%colors.length]])??[]);
 const previousTotal=data?.trend?.at(-2)?.total;
 const delta=s&&previousTotal?((s.total-previousTotal)/previousTotal*100).toFixed(1):null;
 const filterLabels={category:'หมวดสินค้า',product:'สินค้า',cashier:'พนักงาน',terminal:'เครื่อง POS',method:'การชำระเงิน',status:'สถานะ'};
 const appliedFilters=section==='reports'?Object.entries(filter).filter(([,value])=>value).map(([key,value])=>{
  const label=key==='category'?catalog?.categories.find(c=>c.id===value)?.name:key==='product'?catalog?.products.find(p=>p.id===value)?.name:key==='cashier'?data?.users.find(u=>u.id===value)?.name:key==='terminal'?data?.terminals.find(t=>t.id===value)?.name:({CASH:'เงินสด',QR:'QR / โอน',OTHER:'อื่น ๆ',COMPLETED:'สำเร็จ',VOIDED:'ยกเลิก',PARTIALLY_REFUNDED:'คืนเงินบางส่วน',REFUNDED:'คืนเงินครบ'} as Record<string,string>)[value];
  return `${filterLabels[key as keyof typeof filterLabels]}: ${label??value}`;
 }):[];
 async function printA4(){
  if(printingRef.current||loading||!data||loadedParams!==params)return;
  printingRef.current=true;setPrinting(true);const version=requestVersion.current;
  try{await document.fonts.ready;if(version!==requestVersion.current)throw new Error('ข้อมูลรายงานเปลี่ยน กรุณาตรวจสอบแล้วกดพิมพ์อีกครั้ง');window.print();}
  catch(e){setError((e as Error).message);}finally{printingRef.current=false;setPrinting(false);}
 }
 let actualValue:number|null=null;try{if(actual)actualValue=Math.round(Number(actual)*100);if(!/^\d{1,7}(\.\d{1,2})?$/.test(actual))actualValue=null;}catch{}
 const difference=actualValue!==null&&s?actualValue-s.payments.CASH:null;
 if(context==='pos')return <div className="cashier-daily-report">
  <div className="page-heading"><div><span className="eyebrow">สรุปยอดขายสำหรับพนักงานขาย</span><h1>รายงานประจำวัน</h1><p>แสดงยอดสุทธิของแต่ละหมวด และยอดรวมประจำวัน</p></div><div className="page-actions"><input aria-label="วันทำการ" type="date" value={date} disabled={printing} onChange={e=>{setDate(e.target.value);setNotice('');}}/><button className="secondary" disabled={printing||loading} onClick={()=>void load()}><RefreshCw size={16}/>รีเฟรช</button><button className="primary" disabled={printing||loading||!data||loadedParams!==params} onClick={()=>void printDaily()}><Printer size={17}/>{printing?'กำลังพิมพ์…':`พิมพ์ ${catalog?.config.profile.paperMm??'58'} มม.`}</button></div></div>
  {error&&<div role="alert" className="error">{error}</div>}{notice&&<div role="status" className="notice">{notice}</div>}
  {!s?<div className="loading">กำลังคำนวณยอดขาย…</div>:<><div className="pos-daily-total"><div><span>รวมยอดขายประจำวัน</span><small>{reportDate(data!.date)}</small></div><strong>฿{money(s.total)}</strong></div><div className="panel category-report"><div className="panel-title"><h2>ยอดขายแยกตามหมวดสินค้า</h2><span>ยอดสุทธิ (บาท)</span></div><div className="table-scroll"><table><thead><tr><th>หมวดสินค้า</th><th className="number">ยอดขายประจำวัน</th></tr></thead><tbody>{s.categories.map(c=><tr key={c.id}><td>{c.name}</td><td className="number emphasis">{money(c.total)}</td></tr>)}</tbody><tfoot><tr><td>รวมทั้งหมด</td><td className="number">{money(s.total)}</td></tr></tfoot></table></div></div><p className="muted small">ยอดสุทธิหักส่วนลดและคืนเงินแล้ว ไม่รวมบิลยกเลิก</p></>}
 </div>;
 return <><div className="page-heading"><div><span className="eyebrow">SALES & FINANCIAL CONTROL</span><h1>{title}</h1><p>{section==='dashboard'?'ยอดขายประจำวัน แยกตามหมวดสินค้า':'ตรวจสอบยอดขายและเก็บหลักฐานการสรุปยอด'}</p></div><div className="page-actions"><input aria-label="วันทำการ" type="date" value={date} disabled={printing} onChange={e=>{setDate(e.target.value);setActual('');}}/><button className="secondary" disabled={printing||loading} onClick={()=>void load()}><RefreshCw size={16}/>รีเฟรช</button>{can(user.role,'export')&&<a className="secondary" href={`/api/export?${params}`}><Download size={16}/>ส่งออก CSV</a>}<button className="secondary" disabled={printing||loading||!data||loadedParams!==params} onClick={()=>void printA4()}><Printer size={16}/>{printing?'กำลังเตรียมพิมพ์…':'พิมพ์ A4'}</button></div></div>
 {error&&<div role="alert" className="error">{error}</div>}{notice&&<div role="status" className="notice">{notice}</div>}
 {section==='reports'&&<div className="panel report-filters"><label>ตั้งแต่<input type="date" disabled={printing} value={from} onChange={e=>setFrom(e.target.value)}/></label><label>ถึง<input type="date" disabled={printing} value={to} onChange={e=>setTo(e.target.value)}/></label>{(['category','product','cashier','terminal','method','status'] as const).map(key=><label key={key}>{({category:'หมวดสินค้า',product:'สินค้า',cashier:'พนักงาน',terminal:'เครื่อง POS',method:'การชำระเงิน',status:'สถานะ'})[key]}<select aria-label={filterLabels[key]} disabled={printing} value={filter[key]} onChange={e=>setFilter(f=>({...f,[key]:e.target.value}))}><option value="">ทั้งหมด</option>{key==='category'?catalog?.categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>):key==='product'?catalog?.products.map(p=><option key={p.id} value={p.id}>{p.name}</option>):key==='cashier'?data?.users.map(u=><option key={u.id} value={u.id}>{u.name}</option>):key==='terminal'?data?.terminals.map(t=><option key={t.id} value={t.id}>{t.name}</option>):(key==='method'?[['CASH','เงินสด'],['QR','QR/โอน'],['OTHER','อื่น ๆ']]:[['COMPLETED','สำเร็จ'],['VOIDED','ยกเลิก'],['PARTIALLY_REFUNDED','คืนเงินบางส่วน'],['REFUNDED','คืนเงินครบ']]).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>)}</div>}
 {!s?<div className="loading">กำลังคำนวณยอดขาย…</div>:<><div className="report-day">{data?.from===data?.to&&<span className={`badge ${data?.day?.closed?'':'success'}`}>{data?.day?.closed?'ปิดยอดแล้ว':'เปิดขาย'}</span>}<span>{data?.from!==data?.to?`วันที่ ${reportDate(data!.from)} – ${reportDate(data!.to)}`:`วันทำการ ${reportDate(date)} · เริ่ม ${data?.config.opening} น.`}</span>{section==='dashboard'&&<small>อัปเดตทุก 30 วินาที</small>}</div><div className="kpi-grid"><div className="kpi featured"><span><TrendingUp size={18}/>ยอดขายสุทธิ</span><strong>฿{money(s.total)}</strong><small>{delta!==null?`${Number(delta)>=0?'+':''}${delta}% เทียบวันก่อน`:'หลังหักส่วนลดและคืนเงิน'}</small></div><div className="kpi"><span><ReceiptText size={18}/>จำนวนบิล</span><strong>{s.count.toLocaleString()}<small> บิล</small></strong><small>เฉลี่ย ฿{money(s.average)} / บิล</small></div><div className="kpi"><span><ShoppingBag size={18}/>จำนวนสินค้าที่ขาย</span><strong>{s.quantity.toLocaleString()}<small> ชิ้น</small></strong><small>ไม่รวมบิลยกเลิก · ก่อนหักจำนวนคืน</small></div><div className="kpi"><span><Wallet size={18}/>เงินสดตามระบบ</span><strong>{data?.filters?'—':`฿${money(s.payments.CASH)}`}</strong><small>{data?.filters?'ไม่แสดงการชำระเมื่อตัดตามสินค้า':'ยอดที่ต้องนำส่งก่อนเงินตั้งต้น'}</small></div></div>
 {section==='dashboard'&&<DashboardCharts summary={s} trend={data?.trend??[]} days={trendDays} onDaysChange={setTrendDays} loading={loading} categoryColors={categoryColors}/>}
 <div className="panel category-report"><div className="panel-title"><h2>ยอดขายแยกตามหมวดสินค้า</h2><span>คำนวณจากข้อมูลบิลที่บันทึก</span></div><div className="table-scroll"><table><thead><tr><th>หมวดสินค้า</th><th className="number">รวมสุทธิ</th><th className="number">ชิ้น</th></tr></thead><tbody>{s.categories.map((c,i)=><tr key={c.id}><td><span className="category-dot" style={{background:categoryColors[c.id]??colors[i%colors.length]}}/>{c.name}</td><td className="number emphasis">{money(c.total)}</td><td className="number">{c.quantity}</td></tr>)}</tbody><tfoot><tr><td>รวมทั้งหมด</td><td className="number">{money(s.total)}</td><td className="number">{s.quantity}</td></tr></tfoot></table>{!s.categories.length&&<Empty text="ยังไม่มีรายการขายในช่วงที่เลือก"/>}</div></div>
 <div className="two-columns"><div className="panel"><div className="panel-title"><h2>การชำระเงินและปรับยอด</h2></div>{data?.filters?<p className="info">ไม่แสดงยอดชำระเมื่อเลือกเฉพาะหมวดหรือสินค้า เพราะบิลเดียวอาจมีสินค้าหลายหมวด</p>:[['CASH','เงินสด'],['QR','QR / โอน'],['OTHER','อื่น ๆ']].map(([key,label])=><div className="metric-row" key={key}><span>{label}</span><strong>฿{money(s.payments[key]??0)}</strong></div>)}<div className="metric-row"><span>ส่วนลด</span><strong>฿{money(s.discount)}</strong></div><div className="metric-row"><span>ยอดบิลยกเลิก</span><strong>฿{money(s.voided)}</strong></div><div className="metric-row"><span>คืนเงิน</span><strong>฿{money(s.refunded)}</strong></div></div><div className="panel"><div className="panel-title"><h2>สินค้าขายดี 10 อันดับ</h2></div>{s.products.slice(0,10).map((p,i)=><div className="metric-row" key={`${i}-${p.name}`}><span><b className="rank">{i+1}</b>{p.name}<small> {p.quantity} ชิ้น</small></span><strong>฿{money(p.total)}</strong></div>)}{!s.products.length&&<Empty text="ยังไม่มีข้อมูลสินค้า"/>}</div></div>
 {section==='reports'&&<div className="two-columns">{[['cashiers','ยอดขายตามพนักงาน'],['terminals','ยอดขายตามเครื่อง POS']].map(([key,label])=><div className="panel" key={key}><div className="panel-title"><h2>{label}</h2></div>{Object.entries(key==='cashiers'?s.cashiers:s.terminals).map(([id,total])=><div className="metric-row" key={id}><span>{key==='cashiers'?data?.users.find(u=>u.id===id)?.name??id:data?.terminals.find(t=>t.id===id)?.name??id}</span><strong>฿{money(total)}</strong></div>)}</div>)}</div>}
 {section==='closings'&&<div className="two-columns"><div className="panel"><div className="panel-title"><h2>ตรวจนับเงินสดและปิดยอด</h2></div><div className="metric-row"><span>เงินสดตามระบบ</span><strong>฿{money(s.payments.CASH)}</strong></div><label>เงินสดที่นับได้จริง (ไม่รวมเงินตั้งต้น)<input type="number" min="0" step="0.01" value={actual} onChange={e=>setActual(e.target.value)} disabled={data?.day?.closed}/></label><div className={`change ${difference?'difference':''}`}><span>ส่วนต่าง</span><strong>{difference===null?'—':`฿${money(difference)}`}</strong></div><label>หมายเหตุ / เหตุผลส่วนต่าง<textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="จำเป็นเมื่อเงินสดไม่ตรง หรือเปิดรอบแก้ไข"/></label>{can(user.role,'close')&&!data?.day?.closed&&<button className="primary wide" disabled={busy||actualValue===null||!!difference&&!note.trim()} onClick={()=>{if(confirm('ยืนยันปิดยอด? หลังปิดจะไม่สามารถขายหรือปรับบิลในวันนี้'))void run(()=>api('closings',{date,actualCash:actualValue,note}),'ปิดยอดแล้ว');}}><LockKeyhole size={18}/>ปิดยอดประจำวัน</button>}{can(user.role,'reopen')&&data?.day?.closed&&<button className="secondary wide" disabled={busy||note.trim().length<3} onClick={()=>void run(()=>api('closings/day/reopen',{date,note}),'เปิดรอบแก้ไขแล้ว โดยยังเก็บยอดปิดเดิม')}><UnlockKeyhole size={18}/>เปิดรอบแก้ไข</button>}</div><div className="panel"><div className="panel-title"><h2>ประวัติปิดยอด</h2></div>{data?.closings.map(c=><div className="closing-record" key={c.id}><strong>รอบบันทึก {c.revision}</strong><small>{thaiDate(c.createdAt)}</small><div className="metric-row"><span>ยอดสุทธิที่ปิด</span><strong>฿{money(c.summary.total)}</strong></div><div className="metric-row"><span>เงินสดตามระบบ / นับจริง</span><strong>{money(c.expectedCash)} / {money(c.actualCash)}</strong></div><div className="metric-row"><span>ส่วนต่าง</span><strong>฿{money(c.difference)}</strong></div><p>{c.note||'ไม่มีหมายเหตุ'}</p></div>)}{!data?.closings.length&&<Empty text="ยังไม่มีการปิดยอด"/>}</div></div>}
 </>}{data&&typeof document!=='undefined'&&createPortal(<A4SalesReport report={data} title={title} preparedBy={user.name} filters={appliedFilters}/>,document.body)}</>;
}
