import EmbeddedPostgres from 'embedded-postgres';
import { existsSync } from 'node:fs';
const pg = new EmbeddedPostgres({databaseDir:'.local-db',user:'cida',password:'cida_local_only',port:5433,persistent:true,authMethod:'scram-sha-256',postgresFlags:['-h','127.0.0.1'],onLog:()=>{},onError:console.error});
if(!existsSync('.local-db/PG_VERSION'))await pg.initialise();
await pg.start();
const client=pg.getPgClient();await client.connect();
const result=await client.query("SELECT 1 FROM pg_database WHERE datname = 'cida_pos'");
if(!result.rowCount)await client.query('CREATE DATABASE cida_pos');
await client.end();
console.log('Local PostgreSQL ready on 127.0.0.1:5433. Development only.');
for(const signal of ['SIGINT','SIGTERM'])process.on(signal,async()=>{await pg.stop();process.exit(0);});
setInterval(()=>{},60000);
